import {useEffect,useState} from 'react';
import {FlashDeck} from './FlashDeck';
const questions=[['sleepHours','How long did you sleep?','Hours of sleep last night.','0','24','0.1'],['sleepQuality','How was your sleep?','1 = very poor · 10 = excellent','1','10','1'],['soreness','How sore do you feel?','1 = none · 10 = very sore','1','10','1'],['energy','How is your energy?','1 = drained · 10 = full of energy','1','10','1'],['stress','How much stress today?','1 = calm · 10 = very stressed','1','10','1'],['motivation','Ready to move?','1 = very low · 10 = very motivated','1','10','1'],['mood','How are you feeling?','1 = very low · 10 = great','1','10','1']];
export function ReadinessCards({initial,draftKey,onSave,onGoogleFitImport}:{initial:Record<string,any>;draftKey:string;onSave:(values:Record<string,any>)=>Promise<void>;onGoogleFitImport?:()=>Promise<{values:Record<string,any>;labels:string[]}>}) {
 const [values,setValues]=useState<Record<string,any>>(()=>{try{return JSON.parse(localStorage.getItem(draftKey)||'null')||initial;}catch{return initial;}}),[index,setIndex]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[importState,setImportState]=useState<'idle'|'processing'|'imported'|'empty'>('idle'),[importedLabels,setImportedLabels]=useState<string[]>([]),[importStep,setImportStep]=useState('');
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify(values));}catch{setError('Draft could not be saved. Keep this page open.');}},[values,draftKey]);
 const update=(key:string,value:string)=>setValues(v=>({...v,[key]:value}));
 const importGoogleFit=async()=>{if(!onGoogleFitImport)return;setBusy(true);setImportState('processing');setImportStep('Connecting to Google Fit…');setError('');const timer=window.setTimeout(()=>setImportStep('Reading today’s sleep, heart-rate, and steps…'),650);try{const imported=await onGoogleFitImport();setValues(v=>({...v,...Object.fromEntries(Object.entries(imported.values).filter(([,value])=>value!==undefined&&value!==null&&value!==''))}));setImportedLabels(imported.labels);setImportStep('Readings added to this readiness draft.');setImportState('imported');}catch(e){const message=(e as Error).message;setImportStep('');if(/No sleep, heart-rate, or step data/i.test(message)){setImportState('empty');}else{setImportState('idle');setError(message);}}finally{window.clearTimeout(timer);setBusy(false);}};
 return <section className="readiness-cards">{onGoogleFitImport?<><button type="button" className="btn btn-soft" disabled={busy} onClick={()=>void importGoogleFit()}>{importState==='processing'?'⌁ Importing from Google Fit…':importState==='imported'?'✓ Imported into readiness draft':'⌁ Import sleep & vitals from Google Fit'}</button>{importState==='processing'?<p className="subtle">{importStep}</p>:null}{importState==='imported'?<p className="text-ok">✓ Imported {importedLabels.join(', ')} into today’s readiness draft. Review the cards, then select <strong>Save readiness & unlock</strong> to save it for this day.</p>:null}{importState==='empty'?<p className="subtle">Google Fit is connected, but it has no sleep, heart-rate, or step record for today. Complete these values manually.</p>:null}</>:null}<FlashDeck label="Daily check-in" index={index} onIndexChange={setIndex}>
 {questions.map(([key,title,hint,min,max,step],i)=><div key={key}><span className="flash-icon" aria-hidden="true">{['☾','✦','◌','ϟ','≈','↗','☺'][i]}</span><p className="page-eyebrow">A moment for yourself</p><h3>{title}</h3><p className="subtle">{hint}</p>{key==='sleepHours'?<label className="flash-number">Sleep hours<input aria-label="Sleep hours" type="number" min={min} max={max} step={step} required value={values[key]??''} onChange={e=>update(key,e.target.value)}/></label>:<><div className="flash-rating">{Array.from({length:10},(_,j)=><button key={j} type="button" aria-label={`${title} ${j+1}`} aria-pressed={Number(values[key])===j+1} className={Number(values[key])===j+1?'selected':''} onClick={()=>update(key,String(j+1))}>{j+1}</button>)}</div><input className="input" aria-label={title} type="number" min={min} max={max} step={step} required value={values[key]??''} onChange={e=>update(key,e.target.value)}/></>}</div>)}
 <div><span className="flash-icon">◎</span><h3>Anything else to know?</h3><label>Pain or injury?<select className="input" required value={String(values.painFlag??'')} onChange={e=>update('painFlag',e.target.value)}><option value="">Choose an answer</option><option value="false">No pain flagged</option><option value="true">Yes, pain or injury</option></select></label><label>Resting heart rate · optional<input className="input" type="number" min="25" max="250" value={values.restingHeartRate??''} onChange={e=>update('restingHeartRate',e.target.value)}/></label><label>Steps · optional<input className="input" type="number" min="0" value={values.steps??''} onChange={e=>update('steps',e.target.value)}/></label><label>Notes · optional<textarea className="input" value={values.notes??''} onChange={e=>update('notes',e.target.value)}/></label></div>
 <div><span className="flash-icon">✓</span><h3>Your check-in, in perspective.</h3><p className="subtle">These inputs inform an estimated readiness score, not a medical assessment.</p><dl className="flash-review">{questions.map(([key,title])=><div key={key}><dt>{title}</dt><dd>{values[key]??'Not recorded'}</dd></div>)}<div><dt>Pain flagged</dt><dd>{String(values.painFlag)==='true'?'Yes':'No'}</dd></div></dl><button type="button" className="btn btn-hot w-full" disabled={busy} onClick={async()=>{for(let i=0;i<questions.length;i++){const [key,,,min,max]=questions[i];if(values[key]==null||values[key]===''||!Number.isFinite(Number(values[key]))||Number(values[key])<Number(min)||Number(values[key])>Number(max)){setIndex(i);setError('Please complete this answer.');return;}}if(!['true','false'].includes(String(values.painFlag))){setIndex(7);return;}setBusy(true);setError('');try{await onSave(values);localStorage.removeItem(draftKey);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Saving…':'Save readiness & unlock'}</button></div>
 </FlashDeck>{error&&<p role="alert">{error}</p>}<p className="subtle">Private by default · Draft stays on this device</p></section>;
}
