import {test,expect} from '@playwright/test';
test('active set survives reload, finished session saves once, and sync UI is available',async({page,request})=>{
  const readiness={weekId:'e2e-week',dayKey:'Mon',date:'2026-09-07',sleepHours:8,sleepQuality:8,soreness:2,energy:8,stress:2,motivation:8,mood:8,painFlag:false};
  expect((await request.post('/api/readiness',{data:readiness})).ok()).toBeTruthy();
  await page.goto('/');
  await page.getByRole('button',{name:'Start session',exact:true}).first().click();
  const load=page.getByRole('spinbutton',{name:'Set 1 load'}),reps=page.getByRole('spinbutton',{name:'Set 1 reps'});
  await load.fill('60');await reps.fill('8');
  await page.getByRole('button',{name:'+ Set',exact:true}).click();
  const deck=page.getByRole('region',{name:'Workout set cards'});
  await deck.getByRole('button',{name:'Next →',exact:true}).click();
  await page.getByRole('spinbutton',{name:'Set 2 load'}).fill('50');
  await page.getByRole('spinbutton',{name:'Set 2 reps'}).fill('10');
  await deck.getByRole('button',{name:'← Back',exact:true}).click();
  await expect(load).toHaveValue('60');
  await deck.screenshot({path:'scratch/v4-workout-card.png'});
  await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('body-os-tracker-draft')||'{}').currentEntry?.weights?.[0])).toBe('60');
  await page.reload();
  await expect(load).toHaveValue('60');await expect(reps).toHaveValue('8');
  await deck.getByRole('button',{name:'Next →',exact:true}).click();
  await expect(page.getByRole('spinbutton',{name:'Set 2 load'})).toHaveValue('50');
  await page.getByRole('button',{name:'Save & next',exact:true}).click();
  const draft=await page.evaluate(()=>JSON.parse(localStorage.getItem('body-os-tracker-draft')!));
  await page.getByRole('button',{name:'Save workout locally',exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>localStorage.getItem('body-os-tracker-draft'))).toBeNull();
  const retry=await request.post('/api/sessions',{data:draft});
  expect(retry.ok()).toBeTruthy();
  const bootstrap=await (await request.get('/api/bootstrap')).json();
  expect(bootstrap.db.sessions.filter((s:{id:string})=>s.id===draft.id)).toHaveLength(1);
  await page.getByRole('button',{name:'Settings',exact:true}).first().click();
  await expect(page.getByRole('region',{name:'Device sync'})).toBeVisible();
});
test('API rejects invalid measurements and preserves stored records',async({request})=>{
  const bad=await request.post('/api/measurements',{data:{date:'2026-02-30',weight:'invalid'}});
  expect(bad.status()).toBe(400);
  const good=await request.post('/api/measurements',{data:{date:'2026-09-07',weight:80}});
  expect(good.ok()).toBeTruthy();
  const item=await good.json();
  const bootstrap=await (await request.get('/api/bootstrap')).json();
  expect(bootstrap.db.measurements.find((m:{id:string})=>m.id===item.id).weight).toBe(80);
});
