import {useRef,useState} from 'react';
import {Alert,View} from 'react-native';
import {Action,Card,Chip,Heading,Icon,Input,Kicker,Label,Page,Row} from '../ui/kit';
import {useTheme} from '../ui/theme';
import {useBody} from '../state/BodyProvider';
import {useDraft} from '../state/useDraft';
import {deviceId,saveRecord,setPreference} from '../lib/store';
import {signInWithGoogle} from '../lib/firebase-sync';
import {bodyOsFirebaseConfig,bodyOsGoogleWebClientId} from '../../../../src/shared/firebase-config';
export function EntryScreen({onComplete}:{onComplete:()=>Promise<void>}){const {rows,refresh}=useBody(),t=useTheme();const profile=rows<Record<string,unknown>>('profile')[0];const draft=useDraft('onboarding',{step:0,name:String(profile?.payload.displayName||''),units:String(profile?.payload.units||'kg')});const [busy,setBusy]=useState(false),lock=useRef(false);const {step,name,units}=draft.value;async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);try{await action();}catch(e){Alert.alert('Body OS',(e as Error).message);}finally{lock.current=false;setBusy(false);}}
async function finish(){if(!name.trim())throw new Error('Enter your name.');const id=profile?.id||'profile';await saveRecord({id,entityType:'profile',payload:{...profile?.payload,id,displayName:name.trim(),units},updatedAt:new Date().toISOString(),revision:profile?.revision||1,deviceId:await deviceId()},true,profile?.revision||0);await setPreference('onboardingVersion',1);await draft.clear();await refresh();await onComplete();}
return <Page><View style={{paddingTop:18,gap:20}}><Row><Icon name="shield" color={t.lime}/><Kicker>BODY OS · V4.0</Kicker></Row><Row>{[0,1,2].map(i=><View key={i} style={{height:3,flex:1,backgroundColor:i<=step?t.lime:t.line,borderRadius:5}}/>)}</Row>
{step===0?<><View style={{alignItems:'center',gap:18,paddingVertical:20}}><Card><Icon name="shield" size={40} color={t.lime}/></Card><Kicker>Training, recovery & daily care</Kicker><Heading size={36}>Your Body. Your Progress. Your Space.</Heading><Label muted>Your training and care companion, with your records available offline.</Label></View>{[['shield','Available offline','Log workouts and check-ins on this phone, even without an internet connection.'],['progress','Guidance from your records','Review your actual training history, readiness and progress in one place.'],['care','Daily care, together','Keep your routines, products and skin journal alongside your training.']].map(([icon,title,detail])=><Card key={title}><Row><Icon name={icon} color={t.lime}/><Heading size={18}>{title}</Heading></Row><Label muted>{detail}</Label></Card>)}<Action title={busy?'Connecting…':'Continue with Google'} disabled={busy||!draft.loaded} onPress={()=>void run(async()=>{const session=await signInWithGoogle({...bodyOsFirebaseConfig,webClientId:bodyOsGoogleWebClientId});if(session)draft.set({...draft.value,step:1});})}/><Action secondary title="Continue offline" disabled={busy||!draft.loaded} onPress={()=>draft.set({...draft.value,step:1})}/><Label muted size={12}>Google connects your devices. An account is not required for local logging.</Label></>:step===1?<><Kicker>Make it yours</Kicker><Heading>What should we call you?</Heading><Card><Input label="Your name" value={name} onChange={v=>draft.set({...draft.value,name:v})}/><Kicker>Training units</Kicker><Row>{['kg','lb'].map(v=><Chip key={v} title={v==='kg'?'Kilograms':'Pounds'} selected={units===v} onPress={()=>draft.set({...draft.value,units:v})}/>)}</Row></Card><Action title="Continue" onPress={()=>name.trim()?draft.set({...draft.value,step:2}):Alert.alert('Enter your name')}/><Action secondary title="Back" onPress={()=>draft.set({...draft.value,step:0})}/></>:<><Kicker>Ready when you are</Kicker><Heading>One good day at a time.</Heading>{[['01','Check in','Record your readiness and review how you feel.'],['02','Train','Follow a plan, log real sets and save your progress.'],['03','Care','Build a consistent routine and keep your observations.']].map(([n,title,detail])=><Card key={n}><Kicker>{n}</Kicker><Heading size={22}>{title}</Heading><Label muted>{detail}</Label></Card>)}<Action title={busy?'Saving…':'Enter Body OS'} disabled={busy} onPress={()=>void run(finish)}/><Action title="Back" secondary disabled={busy} onPress={()=>draft.set({...draft.value,step:1})}/></>}
{Boolean(draft.error)&&<Label>{draft.error}</Label>}</View></Page>;}
