import {useMemo} from 'react';
import {View} from 'react-native';
import {useBody} from '../state/BodyProvider';
import {useNav} from '../navigation/routes';
import {Action,Card,Destination,Empty,Heading,Kicker,Label,Metric,Page,Row,Ring} from '../ui/kit';
import {localDateKey} from '../../../../src/shared/evidence';
import {computeMetrics} from '../../../../src/shared/metrics';
import {snapshotFromRecords} from '../../../../src/shared/record-snapshot';
import type {Readiness,Session,Week} from '../../../../src/shared/types';
import type {SkinLog} from '../../../../src/shared/skin';
import {TrendChart} from '../components/TrendChart';
export function TodayScreen(){const {rows}=useBody(),nav=useNav(),today=localDateKey();const profile=rows<{displayName:string}>('profile')[0]?.payload;const readiness=rows<Readiness>('readiness').find(r=>r.payload.date===today);const sessions=rows<Session>('session').filter(r=>r.payload.status==='finished');const week=rows<Week>('week').find(r=>r.payload.days.some(d=>d.scheduledDate===today));const day=week?.payload.days.find(d=>d.scheduledDate===today);return <Page><Kicker>{new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</Kicker><Heading>Your day, {profile?.displayName||'your way'}.</Heading><Card accent><Kicker>Today’s training</Kicker><Heading size={25}>{day?.title||'Make room for progress.'}</Heading><Label muted>{day?`${day.exercises.length} movements · ${week?.payload.name}`:'Choose a saved workout or build your own session.'}</Label><Action title="Start or resume workout" icon="train" onPress={()=>nav.navigate('Workout')}/></Card><Card><Row><View style={{flex:1}}><Kicker>Daily readiness</Kicker><Heading size={30}>{readiness?`${readiness.payload.score}/100`:'Not checked in'}</Heading></View>{readiness!=null&&<Label accent>{readiness.payload.band}</Label>}</Row><Label muted>{readiness?.payload.assistant?.reason||'Check in with yourself before training.'}</Label><Action secondary title={readiness?'Review today’s check-in':'Begin check-in'} onPress={()=>readiness?nav.navigate('ReadinessResult',{id:readiness.id}):nav.navigate('Readiness')}/></Card><Card><Kicker>Your consistency</Kicker><Row><Metric title="Finished workouts" value={sessions.length}/><Metric title="This week" value={sessions.filter(r=>{const gap=(Date.now()-new Date(r.payload.date+'T12:00:00').getTime())/86400000;return gap>=0&&gap<7;}).length}/></Row></Card><Destination title="Training Coach" detail="Your briefing and next steps" icon="person" onPress={()=>nav.navigate('Coach')}/><Destination title="Habits & daily actions" icon="check" onPress={()=>nav.navigate('Habits')}/><Destination title="Your weekly review" icon="calendar" onPress={()=>nav.navigate('WeeklyReview')}/><Destination title="Readiness history" icon="progress" onPress={()=>nav.navigate('ReadinessHistory')}/></Page>;}
export function TrainScreen(){const nav=useNav();return <Page><Kicker>Train with intent</Kicker><Heading>Your next good session.</Heading><Card accent><Heading size={24}>Ready when you are.</Heading><Label muted>Follow your plan, log actual work and keep every set.</Label><Action title="Start / resume workout" icon="train" onPress={()=>nav.navigate('Workout')}/></Card><Destination title="Training plans" detail="Weeks, days and prescriptions" icon="book" onPress={()=>nav.navigate('Plans')}/><Destination title="Calendar" detail="Schedule and reschedule your training" icon="calendar" onPress={()=>nav.navigate('Calendar')}/><Destination title="Exercise library" detail="Search movements, equipment and favourites" icon="train" onPress={()=>nav.navigate('Library')}/><Destination title="Programs" detail="Your training phases and weeks" icon="progress" onPress={()=>nav.navigate('Programs')}/><Destination title="Saved splits" detail="Choose and customise a template" icon="book" onPress={()=>nav.navigate('Splits')}/><Destination title="Training Coach" icon="person" onPress={()=>nav.navigate('Coach')}/></Page>;}
export function ProgressScreen(){const {records,units}=useBody(),nav=useNav();const metrics=useMemo(()=>computeMetrics(snapshotFromRecords(records)),[records]);return <Page><Kicker>Your work, over time</Kicker><Heading>Progress overview</Heading><Card><Row><Metric title="Total volume" value={Math.round(metrics.totals.tonnage).toLocaleString()} unit={units}/><Metric title="Sessions" value={metrics.totals.sessions}/></Row><Label muted>Recorded training · working volume</Label></Card>{metrics.weeklyVolume.length?<Card><Kicker>Training volume</Kicker><TrendChart title="Weekly volume" unit={units} points={metrics.weeklyVolume.map(r=>({date:r.weekStart,value:r.tonnage}))}/></Card>:<Empty title="Your progress begins here" detail="Finish a workout to see your training trends."/>}<Destination title="Workout records" icon="book" onPress={()=>nav.navigate('Records')}/><Destination title="Strength & PRs" icon="star" onPress={()=>nav.navigate('Strength')}/><Destination title="Lift history" icon="train" onPress={()=>nav.navigate('LiftHistory')}/><Destination title="Training analytics" detail="Volume, consistency and balance" icon="progress" onPress={()=>nav.navigate('Analytics')}/><Destination title="Goals" icon="check" onPress={()=>nav.navigate('Goals')}/><Destination title="Body measurements" icon="person" onPress={()=>nav.navigate('Body')}/><Destination title="Cardio" icon="clock" onPress={()=>nav.navigate('Cardio')}/><Destination title="Pain & injury log" icon="care" onPress={()=>nav.navigate('Pain')}/><Action title="Reports & exports" icon="book" onPress={()=>nav.navigate('Reports')}/></Page>;}
export function CareScreen(){const {rows}=useBody(),nav=useNav();const log=rows<SkinLog>('skinLog').find(r=>r.payload.date===localDateKey())?.payload;return <Page><Kicker>Daily care</Kicker><Heading>A little consistency.</Heading><Label muted>Your skin, routines and observations in one place.</Label><Card><Kicker>Today’s skin check-in</Kicker>{log?<Row><Metric title="Barrier" value={log.barrier??'—'} unit="/10"/><Metric title="Skin hydration" value={log.hydration??'—'} unit="/10"/></Row>:<Label muted>No observations recorded today.</Label>}<Action title={log?'Review today’s skin':'Log skin check-in'} onPress={()=>nav.navigate('SkinCheckIn')}/></Card><Card accent><Kicker>Your rituals</Kicker><Row><Metric title="AM routine" value={log?.routineDone.am?'Done':'Not logged'}/><Metric title="PM routine" value={log?.routineDone.pm?'Done':'Not logged'}/></Row><Action secondary title="Open AM / PM routines" onPress={()=>nav.navigate('Routines')}/></Card><Destination title="My Skin" detail="Your profile, concerns and goals" icon="person" onPress={()=>nav.navigate('SkinProfile')}/><Destination title="Product shelf" icon="care" onPress={()=>nav.navigate('Products')}/><Destination title="Skin journal" icon="book" onPress={()=>nav.navigate('SkinJournal')}/><Destination title="Skin Coach" icon="person" onPress={()=>nav.navigate('SkinCoach')}/></Page>;}
export function MoreScreen(){const nav=useNav();return <Page><Kicker>Your space</Kicker><Heading>Settings & connections</Heading><Destination title="Google account" icon="person" onPress={()=>nav.navigate('Account')}/><Destination title="Device sync" icon="cloud" onPress={()=>nav.navigate('Sync')}/><Destination title="Backups & restore" icon="shield" onPress={()=>nav.navigate('Backups')}/><Destination title="Profile & units" icon="person" onPress={()=>nav.navigate('Profile')}/><Destination title="Appearance" icon="care" onPress={()=>nav.navigate('Appearance')}/><Destination title="Permissions" detail="Notifications and Health Connect" icon="shield" onPress={()=>nav.navigate('Permissions')}/><Destination title="Reminders" icon="clock" onPress={()=>nav.navigate('Reminders')}/><Destination title="Health Connect" icon="care" onPress={()=>nav.navigate('Health')}/><Destination title="App protection" icon="shield" onPress={()=>nav.navigate('Security')}/><Destination title="PC connection" icon="cloud" onPress={()=>nav.navigate('PC')}/><Destination title="AI providers" icon="person" onPress={()=>nav.navigate('AISettings')}/><Destination title="Help & about" icon="book" onPress={()=>nav.navigate('Help')}/></Page>;}
