import {useMemo,useState} from 'react';
import {Alert,Linking,View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useNav,type RootRoutes} from '../navigation/routes';
import {useBody} from '../state/BodyProvider';
import {Action,Card,Chip,Heading,Input,Kicker,Label,Metric,Page,Row,Empty} from '../ui/kit';
import {defaultExerciseCatalog} from '../../../../src/shared/exercise-catalog';
import type {Exercise} from '../../../../src/shared/types';
import type {SyncRecord} from '../../../../src/shared/sync';
import {deviceId,saveRecord} from '../lib/store';
export function useCatalog(){const {records}=useBody();return useMemo(()=>{const map=new Map<string,SyncRecord<Exercise>>(defaultExerciseCatalog().map(e=>[e.id,{id:e.id,entityType:'exercise',payload:e,deviceId:'builtin',revision:0,updatedAt:''}]));for(const r of records.filter(r=>r.entityType==='exercise')){if(r.deletedAt)map.delete(r.id);else map.set(r.id,r as SyncRecord<Exercise>);}return [...map.values()];},[records]);}
export function LibraryScreen(){const catalog=useCatalog(),nav=useNav();const [query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[limit,setLimit]=useState(25);const matches=catalog.filter(r=>!r.payload.meta?.archived&&(filter!=='Favourites'||r.payload.meta?.favorite)&&(filter!=='Custom'||r.deviceId!=='builtin')&&`${r.payload.name} ${r.payload.muscles.join(' ')} ${r.payload.equipment}`.toLowerCase().includes(query.toLowerCase()));return <Page><Kicker>Movement library</Kicker><Heading>Exercise Library</Heading><Label muted>Your collection of movements, cues and training history.</Label><Input label="Search name, muscle or equipment" value={query} onChange={v=>{setQuery(v);setLimit(25);}}/><Row wrap>{['All','Favourites','Custom'].map(f=><Chip key={f} title={f} selected={filter===f} onPress={()=>setFilter(f)}/>)}</Row><Action title="Add custom exercise" secondary icon="plus" onPress={()=>nav.navigate('ExerciseEditor')}/>{matches.slice(0,limit).map(r=><Card key={r.id}><Kicker>{r.payload.equipment||'Your movement'} · {r.payload.trackingMode==='time'?'Timed':r.payload.trackingMode==='reps'?'Reps only':'Weighted'}</Kicker><Heading size={21}>{r.payload.name}{r.payload.meta?.favorite?' ★':''}</Heading><Label muted>{r.payload.muscles.join(' · ')||'Muscles not specified'}</Label>{Boolean(r.payload.defaultCue)&&<Label muted size={13}>{r.payload.defaultCue}</Label>}<Action secondary title="View movement" onPress={()=>nav.navigate('Exercise',{id:r.id})}/></Card>)}{!matches.length&&<Empty title="No matching movements" detail="Try another name, muscle or equipment."/>}{matches.length>limit&&<Action secondary title={`Show more · ${matches.length} results`} onPress={()=>setLimit(limit+25)}/>}<Card><Row><Metric title="Catalog" value={catalog.length}/><Metric title="Matches" value={matches.length}/></Row></Card></Page>;}
export function ExerciseScreen({route}:NativeStackScreenProps<RootRoutes,'Exercise'>){const catalog=useCatalog(),nav=useNav(),{refresh}=useBody(),[busy,setBusy]=useState(false);const row=catalog.find(r=>r.id===route.params.id);if(!row)return <Page><Empty title="Exercise unavailable" detail="It may have been deleted."/></Page>;const e=row.payload;async function favorite(){if(busy||!row)return;setBusy(true);try{await saveRecord({...row,payload:{...e,meta:{...e.meta,favorite:!e.meta?.favorite}},revision:Math.max(1,row.revision),updatedAt:new Date().toISOString(),deviceId:await deviceId()},true,row.revision);await refresh();}catch(error){Alert.alert('Unable to save',(error as Error).message);}finally{setBusy(false);}}return <Page><Kicker>{e.equipment||'Movement'}</Kicker><Heading>{e.name}</Heading><Card><Kicker>Movement profile</Kicker><Label>{e.muscles.join(' · ')||'No muscles specified'}</Label><Label muted>{e.movementPattern}</Label><Label>{e.defaultCue||'No technique cue saved.'}</Label><Row><Metric title="Rest" value={e.defaultRestSec??'—'} unit="sec"/><Metric title="Tempo" value={e.defaultTempo||'—'}/></Row></Card><Action secondary disabled={busy} title={e.meta?.favorite?'Remove favourite':'Add to favourites'} icon="star" onPress={()=>void favorite()}/>{/^https?:\/\//i.test(e.tutorialLink||'')&&<Action title="Watch tutorial" secondary onPress={()=>void Linking.openURL(e.tutorialLink!).catch(()=>Alert.alert('Unable to open tutorial'))}/>}<Action title="Edit movement" onPress={()=>nav.navigate('ExerciseEditor',{id:row.id})}/><Action title="Lift history" secondary onPress={()=>nav.navigate('LiftHistory')}/></Page>;}
