import {useState} from 'react';
import {Alert} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useBody} from '../state/BodyProvider';
import {useNav,type RootRoutes} from '../navigation/routes';
import {Action,Card,Chip,Destination,Empty,Heading,Input,Kicker,Label,Metric,Page,Row} from '../ui/kit';
import {preference,setPreference} from '../lib/store';
import {localDateKey} from '../../../../src/shared/evidence';
import type {Week} from '../../../../src/shared/types';
export function PlansScreen(){const {rows}=useBody(),nav=useNav(),[query,setQuery]=useState('');const weeks=rows<Week>('week').filter(r=>r.payload.name.toLowerCase().includes(query.toLowerCase()));return <Page><Kicker>Structure your training</Kicker><Heading>Training plans</Heading><Input label="Find a plan" value={query} onChange={setQuery}/><Action title="Create / edit training plan" icon="plus" onPress={()=>nav.navigate('Week')}/>{weeks.map(r=><Card key={r.id}><Kicker>Week {r.payload.weekNumber} · {r.payload.active?'Active':r.payload.status||'Saved'}</Kicker><Heading size={23}>{r.payload.name}</Heading><Row><Metric title="Days" value={r.payload.days.length}/><Metric title="Movements" value={r.payload.days.reduce((n,d)=>n+d.exercises.length,0)}/></Row>{r.payload.days.map(d=><Destination key={d.key} title={d.title} detail={`${d.exercises.length} movements`} onPress={()=>nav.navigate('WorkoutPreview',{weekId:r.id,dayKey:d.key})}/>)}<Action title="Edit week" secondary onPress={()=>nav.navigate('Week',{id:r.id})}/></Card>)}{!weeks.length&&<Empty title="Your next training block" detail="Create a plan or sync an existing one from the web app."/>}</Page>;}
export function WorkoutPreviewScreen({route}:NativeStackScreenProps<RootRoutes,'WorkoutPreview'>){const {rows}=useBody(),nav=useNav(),[busy,setBusy]=useState(false);const week=rows<Week>('week').find(r=>r.id===route.params.weekId)?.payload;const day=week?.days.find(d=>d.key===route.params.dayKey);if(!week||!day)return <Page><Empty title="Workout unavailable" detail="This plan or day may have changed."/></Page>;async function start(){if(busy||!week||!day)return;setBusy(true);try{const existing=await preference<{logs:unknown[]}>('workoutDraft',{logs:[]});if(existing.logs.length){Alert.alert('A workout is already in progress','Resume or finish it before starting another plan.',[{text:'Resume',onPress:()=>nav.navigate('Workout')},{text:'Cancel',style:'cancel'}]);return;}await setPreference('workoutDraft',{id:`mobile-${Date.now()}`,date:localDateKey(),startedAt:new Date().toISOString(),logs:[],weekId:week.id,weekName:week.name,weekNumber:week.weekNumber,dayKey:day.key,dayTitle:day.title,planned:day.exercises.map(e=>e.name),prescriptions:day.exercises});await setPreference('workoutEntryV4',{exercise:day.exercises[0]?.name||'',weight:'',reps:'',duration:'',mode:day.exercises[0]?.trackingMode||'weight_reps',rir:'',rpe:'',type:'work',side:'both',tempo:day.exercises[0]?.tempo||'',rest:String(day.exercises[0]?.restSec||90),timerStart:null,timerBase:0,index:1});nav.navigate('Workout');}catch(e){Alert.alert('Cannot start workout',(e as Error).message);}finally{setBusy(false);}}return <Page><Kicker>{week.name} · {day.type}</Kicker><Heading>{day.title}</Heading><Label muted>{day.subtitle}</Label>{day.exercises.map((e,i)=><Card key={`${e.name}-${i}`}><Kicker>Movement {i+1}{e.supersetGroup?` · Superset ${e.supersetGroup}`:''}</Kicker><Heading size={22}>{e.name}</Heading><Label>{e.vol} · {e.target}</Label><Label muted>{e.cue}</Label><Row><Metric title="Rest" value={e.restSec||'—'} unit="sec"/><Metric title="Tempo" value={e.tempo||'—'}/></Row></Card>)}<Action title="Start this workout" disabled={busy||!day.exercises.length} onPress={()=>void start()}/></Page>;}
