import {useMemo,useState} from 'react';
import {View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useBody} from '../state/BodyProvider';
import {useNav,type RootRoutes} from '../navigation/routes';
import {Action,Card,Chip,Destination,Empty,Heading,Input,Kicker,Label,Metric,Page,Ring,Row} from '../ui/kit';
import {TrendChart} from '../components/TrendChart';
import {computeMetrics} from '../../../../src/shared/metrics';
import {snapshotFromRecords} from '../../../../src/shared/record-snapshot';
import {formatWorkoutSet} from '../../../../src/shared/workout-entry';
import type {Session,Target,Measurement} from '../../../../src/shared/types';
export function RecordsScreen(){const {rows}=useBody(),nav=useNav(),[query,setQuery]=useState('');const sessions=rows<Session>('session').filter(r=>r.payload.status==='finished').sort((a,b)=>b.payload.date.localeCompare(a.payload.date));const matches=sessions.filter(r=>`${r.payload.date} ${r.payload.dayTitle} ${r.payload.logs.map(l=>l.name).join(' ')}`.toLowerCase().includes(query.toLowerCase()));return <Page><Kicker>Training archive</Kicker><Heading>Workout records</Heading><Input label="Find a date, session or exercise" value={query} onChange={setQuery}/>{matches.map(r=><Card key={r.id}><Kicker>{r.payload.date}</Kicker><Heading size={22}>{r.payload.dayTitle}</Heading><Row><Metric title="Movements" value={r.payload.logs.length}/><Metric title="Sets logged" value={r.payload.logs.reduce((n,l)=>n+l.sets.length,0)}/></Row><Label muted>{r.payload.logs.map(l=>l.name).join(' · ')}</Label><Action secondary title="View session" onPress={()=>nav.navigate('Session',{id:r.id})}/></Card>)}{!matches.length&&<Empty title="No workouts found" detail="Finished sessions will appear here. Try a different search if you already have records."/>}<Action title="Reports & exports" secondary onPress={()=>nav.navigate('Reports')}/></Page>;}
export function SessionScreen({route}:NativeStackScreenProps<RootRoutes,'Session'>){const {rows,units}=useBody(),nav=useNav();const row=rows<Session>('session').find(r=>r.id===route.params.id);if(!row)return <Page><Empty title="Session unavailable" detail="It may have been deleted or not yet synced."/></Page>;const s=row.payload;return <Page><Kicker>{s.date} · {s.status}</Kicker><Heading>{s.dayTitle}</Heading><Card><Row><Metric title="Movements" value={s.logs.length}/><Metric title="Sets" value={s.logs.reduce((n,l)=>n+l.sets.length,0)}/><Metric title="Time" value={s.durationMinutes??(s.startedAt&&s.endedAt?Math.round((Date.parse(s.endedAt)-Date.parse(s.startedAt))/60000):'—')} unit="min"/></Row></Card>{s.logs.map((l,i)=><Card key={`${l.name}-${i}`}><Kicker>Movement {i+1} · {l.status}</Kicker><Heading size={21}>{l.name}</Heading>{Boolean(l.target)&&<Label muted>Target: {l.target}</Label>}{l.sets.map((set,j)=><Row key={j}><Label muted>SET {j+1}</Label><View style={{flex:1}}><Label>{formatWorkoutSet(set,units)}</Label></View><Label accent>{set.type||'work'}</Label></Row>)}{!l.sets.length&&<Label muted>No actual sets logged.</Label>}{Boolean(l.journal)&&<Label muted>{l.journal}</Label>}</Card>)}{Boolean(s.notes)&&<Card><Kicker>Session notes</Kicker><Label>{s.notes}</Label></Card>}<Action title="Edit session" onPress={()=>nav.navigate('SessionEditor',{id:s.id})}/><Action title="Create report" secondary onPress={()=>nav.navigate('Reports')}/></Page>;}
export function StrengthScreen(){const {records,units}=useBody(),nav=useNav(),[query,setQuery]=useState('');const m=useMemo(()=>computeMetrics(snapshotFromRecords(records)),[records]);return <Page><Kicker>Your best work</Kicker><Heading>Strength & PRs</Heading><Input label="Find a lift" value={query} onChange={setQuery}/>{m.personalRecords.filter(p=>p.exercise.toLowerCase().includes(query.toLowerCase())).map(p=><Card key={p.exercise}><Kicker>Personal record · {p.date}</Kicker><Heading size={21}>{p.exercise}</Heading><Row><Metric title="Best load" value={p.bestWeight} unit={units}/><Metric title="Estimated 1RM" value={Math.round(p.bestE1rm*10)/10} unit={units}/></Row><Label muted>{p.bestReps} reps recorded at the best load. Estimated strength is not a tested maximum.</Label><TrendChart title="Estimated strength" unit={units} points={(m.e1rmSeries[p.exercise]||[]).map(v=>({date:v.date,value:v.e1rm}))}/>{Boolean(p.sessionId)&&<Action secondary title="View record session" onPress={()=>nav.navigate('Session',{id:p.sessionId!})}/>}</Card>)}{!m.personalRecords.length&&<Empty title="Build your strength history" detail="Record weighted working sets to populate comparable strength records."/>}</Page>;}
export function GoalsScreen(){const {records}=useBody(),nav=useNav(),[filter,setFilter]=useState('active');const m=useMemo(()=>computeMetrics(snapshotFromRecords(records)),[records]);return <Page><Kicker>Direction, not pressure</Kicker><Heading>Your goals</Heading><Row>{['active','completed','all'].map(f=><Chip key={f} title={f} selected={filter===f} onPress={()=>setFilter(f)}/>)}</Row><Action title="Create a goal" icon="plus" onPress={()=>nav.navigate('GoalEditor')}/>{m.goalProgress.filter(g=>filter==='all'||g.status===filter).map(g=><Card key={g.id}><Kicker>{g.type} · {g.status}</Kicker><Heading size={22}>{g.name}</Heading><Ring value={g.percent} label="of goal"/><Row><Metric title="Current" value={g.current} unit={g.unit}/><Metric title="Target" value={g.target} unit={g.unit}/></Row><Action secondary title="View goal" onPress={()=>nav.navigate('Goal',{id:g.id})}/></Card>)}{!m.goalProgress.length&&<Empty title="Give your progress a direction" detail="Add a goal and record check-ins over time."/>}</Page>;}
export function GoalScreen({route}:NativeStackScreenProps<RootRoutes,'Goal'>){const {rows}=useBody(),nav=useNav();const row=rows<Target>('target').find(r=>r.id===route.params.id);if(!row)return <Page><Empty title="Goal unavailable" detail="It may have been removed."/></Page>;const g=row.payload;const checks=rows<{goalId:string;date:string;value:number;note?:string}>('goalCheckIn').filter(r=>r.payload.goalId===g.id).sort((a,b)=>b.payload.date.localeCompare(a.payload.date));return <Page><Kicker>{g.status||'active'}</Kicker><Heading>{g.name}</Heading><Card><Row><Metric title="Current" value={g.current} unit={g.unit}/><Metric title="Target" value={g.target} unit={g.unit}/></Row><Label muted>{g.deadline?`Target date: ${g.deadline}`:'No target date'}</Label></Card><Action title="Add check-in" onPress={()=>nav.navigate('GoalCheckIn',{goalId:g.id})}/><Action secondary title="Edit goal" onPress={()=>nav.navigate('GoalEditor',{id:g.id})}/><Heading size={21}>Check-in history</Heading>{checks.map(r=><Card key={r.id}><Kicker>{r.payload.date}</Kicker><Heading size={26}>{r.payload.value} {g.unit}</Heading>{Boolean(r.payload.note)&&<Label muted>{r.payload.note}</Label>}<Action secondary title="Edit check-in" onPress={()=>nav.navigate('GoalCheckIn',{goalId:g.id,id:r.id})}/></Card>)}{!checks.length&&<Label muted>No check-ins yet.</Label>}</Page>;}
export function BodyScreen(){const {rows,units}=useBody(),nav=useNav(),[metric,setMetric]=useState<'weight'|'waist'|'bodyFat'>('weight');const measurements=rows<Measurement>('measurement').sort((a,b)=>b.payload.date.localeCompare(a.payload.date));const latest=measurements[0]?.payload;return <Page><Kicker>Body composition</Kicker><Heading>Your body, over time.</Heading><Card><Row><Metric title="Body weight" value={latest?.weight||'—'} unit={units}/><Metric title="Body fat" value={latest?.bodyFat||'—'} unit="%"/></Row><Label muted>{latest?`Last recorded ${latest.date}`:'No measurements yet'}</Label></Card><Action title="Log measurements" icon="plus" onPress={()=>nav.navigate('MeasurementEditor')}/><Row wrap>{(['weight','waist','bodyFat'] as const).map(k=><Chip key={k} title={k==='bodyFat'?'Body fat':k} selected={metric===k} onPress={()=>setMetric(k)}/>)}</Row><Card><TrendChart title={metric} unit={metric==='weight'?units:metric==='waist'?(units==='kg'?'cm':'in'):'%'} points={measurements.filter(r=>r.payload[metric]!==''&&r.payload[metric]!=null).map(r=>({date:r.payload.date,value:Number(r.payload[metric])}))}/></Card>{measurements.map(r=><Destination key={r.id} title={r.payload.date} detail={`${r.payload.weight||'Not recorded'} ${units}`} onPress={()=>nav.navigate('MeasurementEditor',{id:r.id})}/>)}</Page>;}
