import {useRef,useState} from 'react';
import {Alert,View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootRoutes} from '../navigation/routes';
import {useNav} from '../navigation/routes';
import {useBody} from '../state/BodyProvider';
import {useDraft} from '../state/useDraft';
import {Action,Card,Chip,Destination,Empty,Heading,Input,Kicker,Label,Loading,Page,Ring,Row} from '../ui/kit';
import {FlashDeck} from '../components/FlashDeck';
import {deviceId,saveRecord} from '../lib/store';
import {localDateKey} from '../../../../src/shared/evidence';
import {normalizeReadiness} from '../../../../src/shared/readiness';
import type {Readiness} from '../../../../src/shared/types';
const ratings=[['sleepQuality','Sleep quality','How restorative did your sleep feel?'],['soreness','Muscle soreness','How sore does your body feel?'],['energy','Energy','Rate your mental and physical energy.'],['stress','Stress','How heavy does life feel today?'],['motivation','Motivation','How ready do you feel to train?'],['mood','Mood','How are you feeling today?']] as const;
export function ReadinessScreen({route}:NativeStackScreenProps<RootRoutes,'Readiness'>){const {rows,refresh}=useBody(),nav=useNav();const existing=rows<Readiness>('readiness').find(r=>route.params?.id?r.id===route.params.id:r.payload.date===localDateKey());const initial={baseRevision:existing?.revision||0,values:existing?Object.fromEntries(['sleepHours',...ratings.map(r=>r[0]),'restingHeartRate','notes'].map(k=>[k,String((existing.payload as unknown as Record<string,unknown>)[k]??'')])):{} as Record<string,string>,pain:existing?.payload.painFlag??null as boolean|null,index:0,date:existing?.payload.date||localDateKey()};
const draft=useDraft(`readiness:${existing?.id||localDateKey()}`,initial),[busy,setBusy]=useState(false),lock=useRef(false);
const {values,pain,index,date}=draft.value;const change=(key:string,value:string)=>draft.set({...draft.value,values:{...values,[key]:value}});
if(!draft.loaded)return <Loading message={draft.error||'Opening your check-in…'}/>;
const valid=(key:string,min:number,max:number)=>values[key]!==undefined&&values[key]!==''&&Number.isFinite(Number(values[key]))&&Number(values[key])>=min&&Number(values[key])<=max;
const canNext=index===0?valid('sleepHours',0,24)&&valid('sleepQuality',1,10):index<=5?valid(ratings[index][0],1,10):index===6?pain!==null:true;
const rating=(key:string)=> <Row wrap>{Array.from({length:10},(_,i)=><Chip key={i} title={String(i+1)} selected={Number(values[key])===i+1} onPress={()=>change(key,String(i+1))}/>)}</Row>;
async function save(){if(lock.current)return;lock.current=true;setBusy(true);try{const result=normalizeReadiness({...values,date,painFlag:pain},rows<Readiness>('readiness').map(r=>r.payload));if(!result.item)throw new Error(result.error);if(pain===null)throw new Error('Choose whether you have pain.');const id=existing?.id||`ready-${date}`;const payload={...existing?.payload,...result.item,id,weekId:existing?.payload.weekId||'daily',dayKey:existing?.payload.dayKey||date};await saveRecord({id,entityType:'readiness',payload,deviceId:await deviceId(),updatedAt:new Date().toISOString(),revision:existing?.revision||1},true,draft.value.baseRevision??existing?.revision??0);await draft.clear();await refresh();nav.replace('ReadinessResult',{id});}catch(e){Alert.alert('Check-in not saved',(e as Error).message);}finally{lock.current=false;setBusy(false);}}
return <Page><Kicker>Daily readiness · {date}</Kicker><FlashDeck label="READINESS CHECK-IN" index={index} onChange={next=>draft.set({...draft.value,index:next})} canNext={canNext}>
<View style={{gap:20}}><Kicker>01 / Sleep & recovery</Kicker><Heading>How much restorative sleep did you get?</Heading><Label muted>Record your sleep duration and your own perception of its quality.</Label><Card><Input label="Sleep duration (hours)" value={values.sleepHours||''} numeric onChange={v=>change('sleepHours',v)}/><Row wrap>{[5,6,7,8,9].map(v=><Chip title={`${v}h`} key={v} selected={Number(values.sleepHours)===v} onPress={()=>change('sleepHours',String(v))}/>)}</Row></Card><Card><Kicker>Quality perception</Kicker><Heading size={32}>{values.sleepQuality||'—'} / 10</Heading>{rating('sleepQuality')}<Label muted size={12}>1 Very poor · 10 Excellent</Label></Card></View>
{ratings.slice(1).map(([key,title,prompt],i)=><View key={key} style={{gap:22}}><Kicker>{String(i+2).padStart(2,'0')} / {title}</Kicker><Heading>{prompt}</Heading><Label muted>Choose the answer that reflects how you feel now.</Label><Card accent><Heading size={42}>{values[key]||'—'} / 10</Heading>{rating(key)}<Label muted size={12}>{key==='stress'||key==='soreness'?'1 Very low · 10 Very high':'1 Very low · 10 Excellent'}</Label></Card><Card><Kicker>Training context</Kicker><Label muted>Your answer contributes to the same readiness calculation used in the web app.</Label></Card></View>)}
<View style={{gap:20}}><Kicker>07 / Pain check</Kicker><Heading>Are you experiencing pain or discomfort?</Heading><Label muted>Choose an answer deliberately. Pain and normal muscle soreness are recorded separately.</Label><Action secondary={pain!==false} title="No pain to report" onPress={()=>draft.set({...draft.value,pain:false})}/><Action secondary={pain!==true} title="Yes — report pain or discomfort" onPress={()=>draft.set({...draft.value,pain:true})}/>{Boolean(pain)&&<Card><Label>Describe the issue in your notes. Your check-in will flag it in training guidance.</Label></Card>}</View>
<View style={{gap:20}}><Heading>Anything else to record?</Heading><Input label="Resting heart rate (optional, bpm)" numeric value={values.restingHeartRate||''} onChange={v=>change('restingHeartRate',v)}/><Input label="Notes (optional)" multiline value={values.notes||''} onChange={v=>change('notes',v)}/><Label muted>You can leave optional fields empty.</Label></View>
<View style={{gap:16}}><Heading>Review your check-in.</Heading><Label muted>Only saving commits this check-in. Swipe back to change an answer.</Label><Card><Label>Sleep duration: {values.sleepHours||'Not answered'} hours</Label>{ratings.map(([key,title])=><Label key={key}>{title}: {values[key]||'Not answered'} / 10</Label>)}<Label>Pain: {pain===null?'Not answered':pain?'Yes':'No'}</Label></Card><Action title={busy?'Saving…':'Save check-in'} disabled={busy} onPress={()=>void save()}/></View>
</FlashDeck>{Boolean(draft.error)&&<Label>{draft.error}</Label>}</Page>;}
export function ReadinessHistoryScreen(){const {rows}=useBody(),nav=useNav();const entries=rows<Readiness>('readiness').sort((a,b)=>b.payload.date.localeCompare(a.payload.date));return <Page><Heading>Readiness history</Heading><Label muted>Your check-ins, in your own words.</Label>{entries.length?entries.map(r=><Destination key={r.id} title={`${r.payload.date} · ${r.payload.score}/100`} detail={`${r.payload.band}${r.payload.painFlag?' · Pain flagged':''}`} onPress={()=>nav.navigate('ReadinessResult',{id:r.id})}/>):<Empty title="Your first check-in" detail="Build a history of how you feel before training." action="Start check-in" onPress={()=>nav.navigate('Readiness')}/>}</Page>;}
export function ReadinessResultScreen({route}:NativeStackScreenProps<RootRoutes,'ReadinessResult'>){const {rows}=useBody(),nav=useNav();const row=rows<Readiness>('readiness').find(r=>r.id===route.params.id);if(!row)return <Page><Empty title="Check-in unavailable" detail="This entry may have been deleted on another device."/></Page>;const r=row.payload;return <Page><Kicker>{r.date} · Saved locally</Kicker><Heading>Your readiness.</Heading><Card><Ring value={r.score} label="estimated readiness"/><Heading size={22}>{r.band}</Heading><Label>{r.assistant?.reason||r.recommendation}</Label>{Boolean(r.painFlag)&&<Label>Pain was flagged in this check-in.</Label>}</Card><Card><Kicker>What you recorded</Kicker><Label>Sleep: {r.sleepHours} hours</Label>{ratings.map(([key,title])=><Row key={key}><View style={{flex:1}}><Label muted>{title}</Label></View><Label>{r[key]} / 10</Label></Row>)}{Boolean(r.notes)&&<Label>{r.notes}</Label>}</Card><Action title="Edit check-in" secondary onPress={()=>nav.navigate('Readiness',{id:row.id})}/><Action title="Go to training" onPress={()=>nav.navigate('Train')}/></Page>;}
