import {readField,writeField} from '../lib/editor-fields';
import type {SyncRecord} from '../../../../src/shared/sync';
import {useRef,useState} from 'react';
import {Alert,Switch,View} from 'react-native';
import {Action,Card,Chip,Heading,Input,Kicker,Label,Loading,Page,Row} from '../ui/kit';
import {useBody} from '../state/BodyProvider';
import {useNav} from '../navigation/routes';
import {useDraft} from '../state/useDraft';
import {deviceId,saveRecord} from '../lib/store';
import type {RecordSpec} from '../components/RecordManager';
import {dateKeySchema} from '../../../../src/shared/schemas';
import {localDateKey} from '../../../../src/shared/evidence';
export function RecordEditor({spec,id,title,after,source}:{spec:RecordSpec;id?:string;title?:string;after?:()=>void;source?:SyncRecord<Record<string,unknown>>}){const {records,rows,refresh}=useBody(),nav=useNav();const original=rows<Record<string,unknown>>(spec.type).find(r=>r.id===(id||spec.singleton))||source;const draft=useDraft<Record<string,unknown>>(`editor:${spec.type}:${id||spec.singleton||'new'}`,{...(original?.payload||{date:localDateKey(),...spec.defaults}),__baseRevision:original?.revision||0});const [busy,setBusy]=useState(false),lock=useRef(false);const form=draft.value;const change=(key:string,value:unknown)=>draft.set({...writeField(form,key,value),...Object.fromEntries(spec.fields.filter(f=>f.dayOf===key).map(f=>[f.key,'']))});
async function commit(deleting=false){if(lock.current)return;lock.current=true;setBusy(true);try{let payload={...form};delete payload.__baseRevision;if(!deleting)for(const f of spec.fields){const raw=readField(payload,f.key),empty=raw==null||String(raw).trim()==='';if(f.required&&empty)throw new Error(`${f.label} is required.`);if(empty){payload=writeField(payload,f.key,f.kind==='list'?[]:f.kind==='boolean'?false:'');continue;}if(f.kind==='number'){const n=Number(raw);if(!Number.isFinite(n)||f.min!=null&&n<f.min||f.max!=null&&n>f.max)throw new Error(`Check ${f.label}.`);payload=writeField(payload,f.key,n);}else if(f.kind==='date'&&!dateKeySchema.safeParse(raw).success)throw new Error(`${f.label}: enter a real YYYY-MM-DD date.`);else if(f.kind==='list')payload=writeField(payload,f.key,Array.isArray(raw)?raw:String(raw).split(',').map(x=>x.trim()).filter(Boolean));if(f.options&&!f.options.includes(String(raw)))throw new Error(`Choose ${f.label}.`);if(f.reference&&!records.some(r=>r.entityType===f.reference&&r.id===raw&&!r.deletedAt))throw new Error(`Choose an existing ${f.label}.`);}
const now=new Date().toISOString(),recordId=original?.id||spec.singleton||`${spec.type}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;await saveRecord({id:recordId,entityType:spec.type,payload:{...payload,id:recordId,createdAt:payload.createdAt||now,updatedAt:now},updatedAt:now,deviceId:await deviceId(),revision:original?.revision||1,...(deleting?{deletedAt:now}:{})},true,Number(form.__baseRevision??original?.revision??0));await draft.clear();await refresh();after?after():nav.goBack();}catch(e){Alert.alert('Unable to save',(e as Error).message);}finally{lock.current=false;setBusy(false);}}
if(!draft.loaded)return <Loading message={draft.error||'Opening your draft…'}/>;
return <Page><Kicker>{original?'Edit record':'New record'} · Saved locally</Kicker><Heading>{title||spec.title}</Heading><Label muted>Your draft is kept on this device until you save or discard it.</Label>{spec.fields.map(f=><Card key={f.key}><Kicker>{f.label}{f.required?' *':''}</Kicker>{f.kind==='boolean'?<Switch accessibilityLabel={f.label} value={Boolean(readField(form,f.key))} onValueChange={v=>change(f.key,v)}/>:f.options?<Row wrap>{f.options.map(v=><Chip key={v} title={v} selected={readField(form,f.key)===v} onPress={()=>change(f.key,v)}/>)}</Row>:f.reference?<View style={{gap:8}}>{records.filter(r=>r.entityType===f.reference&&!r.deletedAt).map(r=><Chip key={r.id} title={String((r.payload as Record<string,unknown>).name||(r.payload as Record<string,unknown>).title||r.id)} selected={readField(form,f.key)===r.id} onPress={()=>change(f.key,r.id)}/>)}</View>:f.dayOf?<Row wrap>{((records.find(r=>r.entityType==='week'&&r.id===form[f.dayOf!])?.payload as {days?:{key:string;title:string}[]})?.days||[]).map(d=><Chip key={d.key} title={d.title} selected={readField(form,f.key)===d.key} onPress={()=>change(f.key,d.key)}/>)}</Row>:<Input label={f.kind==='date'?'YYYY-MM-DD':f.kind==='list'?'Separate items with commas':f.label} value={Array.isArray(readField(form,f.key))?(readField(form,f.key) as string[]).join(', '):String(readField(form,f.key)??'')} onChange={v=>change(f.key,v)} numeric={f.kind==='number'} multiline={f.key==='notes'||f.key==='note'}/>}</Card>)}{Boolean(draft.error)&&<Label>{draft.error}</Label>}<Action title={busy?'Saving…':'Save changes'} disabled={busy} icon="check" onPress={()=>void commit()}/><Action title="Discard draft" secondary disabled={busy} onPress={()=>Alert.alert('Discard unsaved changes?','Your saved record will remain unchanged.',[{text:'Keep editing',style:'cancel'},{text:'Discard',style:'destructive',onPress:()=>void draft.clear().then(()=>nav.goBack())}])}/>{original&&!spec.singleton&&<Action title="Delete record" secondary disabled={busy} onPress={()=>Alert.alert('Delete this record?','Deletion will also sync to your other devices.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void commit(true)}])}/>}</Page>;}
