import {useRef,useState} from 'react';
import {Alert} from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import {File,Paths} from 'expo-file-system';
import {Action,Card,Chip,Heading,Kicker,Label,Metric,Page,Row} from '../ui/kit';
import {useBody} from '../state/BodyProvider';
import {snapshotFromRecords} from '../../../../src/shared/record-snapshot';
import {reportHtml} from '../../../../src/shared/report-html';
import {sessionsToCsv} from '../../../../src/shared/training';
export function ReportsScreen(){const {records}=useBody(),[kind,setKind]=useState<'progress'|'week'|'session'>('progress'),[id,setId]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false),db=snapshotFromRecords(records);async function exportFile(csv=false){if(lock.current)return;lock.current=true;setBusy(true);try{if(!csv&&kind!=='progress'&&!id)throw new Error('Select a session or week first.');let uri:string;if(csv){const file=new File(Paths.cache,`body-os-workouts-${Date.now()}.csv`);file.create();file.write(sessionsToCsv(db.sessions));uri=file.uri;}else uri=(await Print.printToFileAsync({html:reportHtml(db,kind,id||undefined)})).uri;if(!await Sharing.isAvailableAsync())throw new Error('File sharing is not available.');await Sharing.shareAsync(uri,{mimeType:csv?'text/csv':'application/pdf'});}catch(e){Alert.alert('Export failed',(e as Error).message);}finally{lock.current=false;setBusy(false);}}return <Page><Kicker>Your training, ready to share</Kicker><Heading>Reports Hub</Heading><Card><Row><Metric title="Workout records" value={db.sessions.filter(s=>s.status==='finished').length}/><Metric title="Saved weeks" value={db.weeks.length}/></Row></Card><Card accent><Kicker>Create your report</Kicker><Heading size={23}>{kind==='progress'?'Progress overview':kind==='week'?'Training week':'Workout session'}</Heading><Row wrap>{(['progress','week','session'] as const).map(k=><Chip key={k} title={k} selected={kind===k} onPress={()=>{setKind(k);setId('');}}/>)}</Row><Label muted>Reports use your saved records and the same shared calculations as the web app.</Label>{kind==='week'&&db.weeks.map(w=><Chip key={w.id} title={w.name} selected={id===w.id} onPress={()=>setId(w.id)}/>)}{kind==='session'&&db.sessions.filter(s=>s.status==='finished').sort((a,b)=>b.date.localeCompare(a.date)).map(s=><Chip key={s.id} title={`${s.date} · ${s.dayTitle}`} selected={id===s.id} onPress={()=>setId(s.id)}/>)}<Action title={busy?'Preparing file…':'Generate & share PDF'} disabled={busy} onPress={()=>void exportFile()}/></Card><Card><Kicker>Data export</Kicker><Heading size={22}>Workout CSV</Heading><Label muted>Export your actual recorded sets for spreadsheets and analysis.</Label><Action title="Export workout CSV" secondary disabled={busy} onPress={()=>void exportFile(true)}/></Card></Page>;}
