import {useRef,useState} from 'react';
import {Alert,View} from 'react-native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useBody} from '../state/BodyProvider';
import {useNav,type RootRoutes} from '../navigation/routes';
import {useDraft} from '../state/useDraft';
import {deviceId,saveRecord} from '../lib/store';
import {Action,Card,Chip,Empty,Heading,Input,Kicker,Label,Loading,Page,Row} from '../ui/kit';
import {parseWorkoutSet} from '../../../../src/shared/workout-entry';
import {sessionInputSchema,dateKeySchema} from '../../../../src/shared/schemas';
import type {Session,SetLog} from '../../../../src/shared/types';
export function SessionEditorScreen({route}:NativeStackScreenProps<RootRoutes,'SessionEditor'>){const {rows,refresh,units}=useBody(),nav=useNav();const original=rows<Session>('session').find(r=>r.id===route.params.id);const draft=useDraft<Session|null>(`session-edit:${route.params.id}`,original?.payload||null);const [busy,setBusy]=useState(false),lock=useRef(false);if(!draft.loaded)return <Loading/>;if(!draft.value||!original)return <Page><Empty title="Session unavailable" detail="The session may have been deleted."/></Page>;const s=draft.value,row=original;const updateSet=(li:number,si:number,patch:Partial<SetLog>)=>draft.set({...s,logs:s.logs.map((l,i)=>i===li?{...l,sets:l.sets.map((set,j)=>j===si?{...set,...patch}:set)}:l)});
async function save(deleted=false){if(lock.current)return;lock.current=true;setBusy(true);try{if(!deleted){if(!dateKeySchema.safeParse(s.date).success)throw new Error('Enter a valid session date.');for(const log of s.logs){if(!log.name.trim())throw new Error('Every movement needs a name.');log.sets=log.sets.map((set,i)=>({...parseWorkoutSet({...set,s:i+1},set.trackingMode||log.trackingMode||'weight_reps'),s:i+1}));}sessionInputSchema.parse(s);}const now=new Date().toISOString();await saveRecord({...row,payload:{...s,updatedAt:now},updatedAt:now,deviceId:await deviceId(),...(deleted?{deletedAt:now}:{})},true,row.revision);await draft.clear();await refresh();if(deleted)nav.navigate('Records');else nav.goBack();}catch(e){Alert.alert('Session not saved',(e as Error).message);}finally{lock.current=false;setBusy(false);}}
return <Page><Kicker>Edit recorded workout</Kicker><Heading>{s.dayTitle}</Heading><Card><Input label="Session title" value={s.dayTitle} onChange={dayTitle=>draft.set({...s,dayTitle})}/><Input label="Session date · YYYY-MM-DD" value={s.date} onChange={date=>draft.set({...s,date})}/><Input label="Session notes" multiline value={s.notes||''} onChange={notes=>draft.set({...s,notes})}/></Card>{s.logs.map((l,li)=><Card key={li}><Kicker>Movement {li+1}</Kicker><Input label="Exercise" value={l.name} onChange={name=>draft.set({...s,logs:s.logs.map((v,i)=>i===li?{...v,name}:v)})}/>{l.sets.map((set,si)=><Card key={si}><Kicker>Set {si+1}</Kicker><Row wrap>{(['weight_reps','reps','time'] as const).map(mode=><Chip key={mode} title={mode==='weight_reps'?'Weighted':mode==='reps'?'Reps':'Timed'} selected={(set.trackingMode||l.trackingMode||'weight_reps')===mode} onPress={()=>updateSet(li,si,{trackingMode:mode})}/>)}</Row>{(set.trackingMode||l.trackingMode)==='time'?<Input label="Duration seconds" numeric value={String(set.durationSec??'')} onChange={v=>updateSet(li,si,{durationSec:v})}/>:<Row>{(set.trackingMode||l.trackingMode||'weight_reps')==='weight_reps'&&<View style={{flex:1}}><Input label={`Load · ${units}`} numeric value={String(set.w)} onChange={w=>updateSet(li,si,{w})}/></View>}<View style={{flex:1}}><Input label="Reps" numeric value={String(set.r)} onChange={r=>updateSet(li,si,{r})}/></View></Row>}<Row><View style={{flex:1}}><Input label="RIR" numeric value={String(set.rir??'')} onChange={rir=>updateSet(li,si,{rir})}/></View><View style={{flex:1}}><Input label="RPE" numeric value={String(set.rpe??'')} onChange={rpe=>updateSet(li,si,{rpe})}/></View></Row><Row wrap>{['warmup','work','amrap','drop','failure','backoff'].map(type=><Chip key={type} title={type} selected={(set.type||'work')===type} onPress={()=>updateSet(li,si,{type})}/>)}</Row><Action title="Remove set" secondary onPress={()=>draft.set({...s,logs:s.logs.map((v,i)=>i===li?{...v,sets:v.sets.filter((_,j)=>j!==si)}:v)})}/></Card>)}<Action title="Add set" secondary onPress={()=>draft.set({...s,logs:s.logs.map((v,i)=>i===li?{...v,sets:[...v.sets,{s:v.sets.length+1,w:'',r:'',type:'work',trackingMode:v.trackingMode||'weight_reps'}]}:v)})}/><Input label="Exercise notes" multiline value={l.journal||''} onChange={journal=>draft.set({...s,logs:s.logs.map((v,i)=>i===li?{...v,journal}:v)})}/></Card>)}<Action title="Add movement" secondary onPress={()=>draft.set({...s,logs:[...s.logs,{name:'',target:'',status:'completed',sets:[]}]})}/><Action title={busy?'Saving…':'Save session changes'} disabled={busy} onPress={()=>void save()}/><Action title="Delete session" secondary disabled={busy} onPress={()=>Alert.alert('Delete this workout?','This deletion will sync to your other devices.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void save(true)}])}/>{Boolean(draft.error)&&<Label>{draft.error}</Label>}</Page>;}
