import {useCallback,useRef,useState} from 'react';
import {Alert,Switch,View} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useNav,type RootRoutes} from '../navigation/routes';
import {useBody} from '../state/BodyProvider';
import {readDraft,writeDraft,clearDraft,flushDraft} from '../lib/drafts';
import {deviceId,saveRecordsAtomically} from '../lib/store';
import {Action,Card,Chip,Heading,Input,Kicker,Label,Loading,Metric,Page,Row} from '../ui/kit';
import {useCatalog} from './LibraryScreens';
import {dateKeySchema} from '../../../../src/shared/schemas';
import {localDateKey} from '../../../../src/shared/evidence';
import type {Week,WeekDay,PlannedExercise} from '../../../../src/shared/types';
import type {SyncRecord} from '../../../../src/shared/sync';
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function useWeekDraft(id:string){const {rows}=useBody();const original=rows<Week>('week').find(r=>r.id===id);const [plan,setPlan]=useState<Week|null>(null),[error,setError]=useState('');const key=`week:${id}`;
useFocusEffect(useCallback(()=>{let active=true;void(async()=>{await flushDraft(key);const value=await readDraft<Week>(key,original?.payload||{id,name:'',weekNumber:1,startDate:localDateKey(),notes:'',active:false,days:[]});if(active)setPlan(value);})().catch(e=>setError(e.message));return()=>{active=false;};},[key,original?.revision]));
async function update(next:Week){setPlan(next);await writeDraft(key,next);}return {plan,update,original,key,error};}
export function WeekEditorScreen({route}:NativeStackScreenProps<RootRoutes,'Week'>){const id=useRef(route.params?.id||`week-${uid()}`).current;const {plan,update,original,key,error}=useWeekDraft(id),nav=useNav(),{refresh,rows}=useBody(),[busy,setBusy]=useState(false),lock=useRef(false);if(!plan)return <Loading message={error||'Opening week…'}/>;const p=plan;async function save(){if(lock.current)return;lock.current=true;setBusy(true);try{if(!p.name.trim()||!dateKeySchema.safeParse(p.startDate).success)throw new Error('Enter a name and a real start date.');if(!p.days.length)throw new Error('Add at least one day.');for(const d of p.days){if(!d.title.trim())throw new Error('Each day needs a title.');for(const e of d.exercises)if(!e.name.trim()||!e.vol.trim())throw new Error('Each movement needs a name and prescription.');}await flushDraft(key);const now=new Date().toISOString(),device=await deviceId(),changes:SyncRecord[]=[{id:p.id,entityType:'week',payload:p,updatedAt:now,revision:original?.revision||1,deviceId:device}];if(p.active){for(const other of rows<Week>('week').filter(row=>row.id!==p.id&&row.payload.active))changes.push({id:other.id,entityType:'week',payload:{...other.payload,active:false},updatedAt:now,revision:other.revision,deviceId:device});const workspace=rows<{activeWeekId:string}>('workspaceState')[0];changes.push({id:'workspace-state',entityType:'workspaceState',payload:{activeWeekId:p.id},updatedAt:now,revision:workspace?.revision||1,deviceId:device});}await saveRecordsAtomically(changes);await clearDraft(key);await refresh();nav.goBack();}catch(e){Alert.alert('Week not saved',(e as Error).message);}finally{lock.current=false;setBusy(false);}}
return <Page><Kicker>Week editor</Kicker><Heading>{p.name||'Build your training week'}</Heading><Card><Input label="Plan name" value={p.name} onChange={name=>void update({...p,name})}/><Row><View style={{flex:1}}><Input label="Week number" numeric value={String(p.weekNumber)} onChange={weekNumber=>void update({...p,weekNumber})}/></View><View style={{flex:2}}><Input label="Start date · YYYY-MM-DD" value={p.startDate} onChange={startDate=>void update({...p,startDate})}/></View></Row><Input label="Mission / notes" value={p.notes} multiline onChange={notes=>void update({...p,notes})}/><Row><Label>Active plan</Label><Switch value={p.active} onValueChange={active=>void update({...p,active})}/></Row></Card><Kicker>Days & movement sequence</Kicker>{p.days.map((d,i)=><Card key={d.key}><Kicker>Day {i+1} · {d.type}</Kicker><Heading size={22}>{d.title}</Heading><Label muted>{d.exercises.length} movements · {d.muscles.join(', ')}</Label><Action title="Edit this day" secondary onPress={()=>nav.navigate('Day',{weekId:id,dayKey:d.key})}/><Row><Chip title="Move up" onPress={()=>{if(!i)return;const days=[...p.days];[days[i-1],days[i]]=[days[i],days[i-1]];void update({...p,days});}}/><Chip title="Remove day" onPress={()=>Alert.alert('Remove day?','This changes the plan draft, not previous workouts.',[{text:'Keep',style:'cancel'},{text:'Remove',style:'destructive',onPress:()=>void update({...p,days:p.days.filter((_,j)=>j!==i)})}])}/></Row></Card>)}<Action secondary title="Add training / rest day" icon="plus" onPress={()=>void (async()=>{const dayKey=`day-${uid()}`;await update({...p,days:[...p.days,{key:dayKey,title:'New day',type:'training',subtitle:'',muscles:[],exercises:[]}]});nav.navigate('Day',{weekId:id,dayKey});})()}/><Action title={busy?'Saving…':'Save & complete week'} disabled={busy} onPress={()=>void save()}/></Page>;}
export function DayEditorScreen({route}:NativeStackScreenProps<RootRoutes,'Day'>){const {plan,update,error}=useWeekDraft(route.params.weekId),nav=useNav();const day=plan?.days.find(d=>d.key===route.params.dayKey);if(!plan||!day)return <Loading message={error||'Opening training day…'}/>;const p=plan,d=day;const change=(patch:Partial<WeekDay>)=>update({...p,days:p.days.map(v=>v.key===d.key?{...d,...patch}:v)});return <Page><Kicker>Day editor · {p.name}</Kicker><Heading>{d.title}</Heading><Card><Input label="Day title" value={d.title} onChange={title=>void change({title})}/><Input label="Focus / subtitle" value={d.subtitle} onChange={subtitle=>void change({subtitle})}/><Input label="Muscles (comma-separated)" value={d.muscles.join(', ')} onChange={v=>void change({muscles:v.split(',').map(s=>s.trim()).filter(Boolean)})}/><Input label="Scheduled date (optional YYYY-MM-DD)" value={d.scheduledDate||''} onChange={scheduledDate=>void change({scheduledDate})}/><Row>{['training','rest','recovery'].map(type=><Chip key={type} title={type} selected={d.type===type} onPress={()=>void change({type})}/>)}</Row></Card>{d.exercises.map((e,i)=><Card key={i}><Kicker>Movement {i+1}{e.supersetGroup?` · Superset ${e.supersetGroup}`:''}</Kicker><Heading size={21}>{e.name}</Heading><Label>{e.vol} · {e.target}</Label><Label muted>{e.cue}</Label><Action title="Edit prescription" secondary onPress={()=>nav.navigate('Prescription',{weekId:p.id,dayKey:d.key,index:i})}/><Row><Chip title="Move up" onPress={()=>{if(!i)return;const exercises=[...d.exercises];[exercises[i-1],exercises[i]]=[exercises[i],exercises[i-1]];void change({exercises});}}/><Chip title="Remove" onPress={()=>void change({exercises:d.exercises.filter((_,j)=>j!==i)})}/></Row></Card>)}<Action title="Add movement" secondary icon="plus" onPress={()=>nav.navigate('Prescription',{weekId:p.id,dayKey:d.key})}/><Action title="Save day to week draft" onPress={()=>void change({}).then(()=>nav.goBack())}/></Page>;}
export function PrescriptionScreen({route}:NativeStackScreenProps<RootRoutes,'Prescription'>){const {plan,update,error}=useWeekDraft(route.params.weekId),nav=useNav(),catalog=useCatalog();const [query,setQuery]=useState(''),[form,setForm]=useState<PlannedExercise|null>(null);const day=plan?.days.find(d=>d.key===route.params.dayKey);const index=route.params.index;
const current=form||day?.exercises[index??-1]||{name:'',vol:'',target:'',cue:'',trackingMode:'weight_reps'};const change=(patch:Partial<PlannedExercise>)=>setForm({...current,...patch});if(!plan||!day)return <Loading message={error||'Opening prescription…'}/>;const p=plan,d=day;async function save(){try{if(!current.name.trim()||!current.vol.trim())throw new Error('Choose a movement and enter its prescription.');for(const [key,max] of [['restSec',86400],['rirTarget',10],['rpeTarget',10],['percent1rm',200]] as const){const value=current[key];if(value!==''&&value!=null&&(!Number.isFinite(Number(value))||Number(value)<0||Number(value)>max))throw new Error(`Check ${key}.`);}const exercises=[...d.exercises];if(index===undefined)exercises.push(current);else exercises[index]=current;await update({...p,days:p.days.map(v=>v.key===d.key?{...d,exercises}:v)});nav.goBack();}catch(e){Alert.alert('Prescription not saved',(e as Error).message);}}
return <Page><Kicker>Prescription editor</Kicker><Heading>{current.name||'Add a movement'}</Heading><Input label="Search the library" value={query} onChange={setQuery}/>{Boolean(query)&&catalog.filter(r=>r.payload.name.toLowerCase().includes(query.toLowerCase())).slice(0,8).map(r=><Action key={r.id} title={r.payload.name} secondary onPress={()=>{change({name:r.payload.name,exerciseId:r.id,familyId:r.payload.familyId,trackingMode:r.payload.trackingMode||'weight_reps',cue:r.payload.defaultCue||'',restSec:r.payload.defaultRestSec??90});setQuery('');}}/>)}<Card><Input label="Exercise name" value={current.name} onChange={name=>change({name})}/><Input label="Volume prescription (for example 3 × 8–12)" value={current.vol} onChange={vol=>change({vol})}/><Input label="Target" value={current.target} onChange={target=>change({target})}/><Row wrap>{(['weight_reps','reps','time'] as const).map(trackingMode=><Chip key={trackingMode} title={trackingMode==='weight_reps'?'Weighted':trackingMode==='reps'?'Reps only':'Timed'} selected={current.trackingMode===trackingMode} onPress={()=>change({trackingMode})}/>)}</Row></Card><Card><Kicker>Intensity & execution</Kicker>{(['restSec','tempo','rirTarget','rpeTarget','percent1rm','supersetGroup'] as const).map(key=><Input key={key} label={key} value={String(current[key]??'')} onChange={v=>change({[key]:v})} numeric={!['tempo','supersetGroup'].includes(key)}/>)}</Card><Card><Input label="Technique cue" multiline value={current.cue} onChange={cue=>change({cue})}/><Input label="Notes" multiline value={current.notes||''} onChange={notes=>change({notes})}/></Card><Action title="Apply prescription to day" onPress={()=>void save()}/></Page>;}
