import {useFocusEffect} from '@react-navigation/native';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Alert,View} from 'react-native';
import {Action,Card,Chip,Heading,Input,Kicker,Label,Loading,Metric,Page,Row} from '../ui/kit';
import {useBody} from '../state/BodyProvider';
import {useNav} from '../navigation/routes';
import {deviceId,preference,saveRecord,setPreference} from '../lib/store';
import {useCatalog} from './LibraryScreens';
import {FlashDeck} from '../components/FlashDeck';
import {RestTimer} from '../components/RestTimer';
import {WorkoutTools} from '../components/WorkoutTools';
import {startRest} from '../lib/reminders';
import {formatWorkoutSet,logFromPlan,parseWorkoutSet} from '../../../../src/shared/workout-entry';
import {localDateKey} from '../../../../src/shared/evidence';
import {sessionInputSchema} from '../../../../src/shared/schemas';
import type {ExerciseLog,ExerciseTrackingMode,PlannedExercise,Readiness,Session} from '../../../../src/shared/types';
type WorkoutDraft={id:string;date:string;startedAt:string;logs:ExerciseLog[];weekId?:string;weekName?:string;weekNumber?:number|string;dayKey?:string;dayTitle?:string;planned?:string[];prescriptions?:PlannedExercise[];setOrder?:string[];};
const fresh=():WorkoutDraft=>({id:`mobile-${Date.now()}`,date:localDateKey(),startedAt:new Date().toISOString(),logs:[]});
type Entry={exercise:string;weight:string;reps:string;duration:string;mode:ExerciseTrackingMode;rir:string;rpe:string;type:string;side:string;tempo:string;rest:string;timerStart:number|null;timerBase:number;index:number;};
const empty:Entry={exercise:'',weight:'',reps:'',duration:'',mode:'weight_reps',rir:'',rpe:'',type:'work',side:'both',tempo:'',rest:'90',timerStart:null,timerBase:0,index:0};
export function WorkoutScreen(){const {records,rows,units,refresh}=useBody(),nav=useNav(),catalog=useCatalog();const [draft,setDraft]=useState<WorkoutDraft>(fresh),[entry,setEntry]=useState<Entry>(empty),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[now,setNow]=useState(Date.now()),[restVersion,setRestVersion]=useState(0);const queue=useRef(Promise.resolve()),lock=useRef(false);const current=useRef(entry);current.current=entry;
useFocusEffect(useCallback(()=>{let active=true;void(async()=>{try{await queue.current;const d=await preference('workoutDraft',fresh());const legacy=await preference('workoutEntry',{exercise:'',weight:'',reps:'',rir:''});const advanced=await preference('workoutAdvanced',{});const e=await preference<Entry>('workoutEntryV4',{...empty,...legacy,...advanced});if(active){setDraft(d);setEntry(e);setLoaded(true);}}catch(e){setError((e as Error).message);}})();const tick=setInterval(()=>setNow(Date.now()),300);return()=>{active=false;clearInterval(tick);};},[]));
function change(patch:Partial<Entry>){const next={...current.current,...patch};current.current=next;setEntry(next);queue.current=queue.current.catch(()=>{}).then(()=>setPreference('workoutEntryV4',next)).catch(e=>setError((e as Error).message));}
const duration=entry.timerStart===null?Number(entry.duration)||0:entry.timerBase+Math.max(0,Math.floor((now-entry.timerStart)/1000));
const prescription=draft.prescriptions?.find(p=>p.name===entry.exercise);const currentLog=draft.logs.find(l=>l.name===entry.exercise);const last=rows<Session>('session').filter(r=>r.payload.status==='finished').sort((a,b)=>b.payload.date.localeCompare(a.payload.date)).find(r=>r.payload.logs.some(l=>l.name===entry.exercise))?.payload;
async function perform(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await queue.current;await action();}catch(e){setError((e as Error).message);Alert.alert('Workout',(e as Error).message);}finally{lock.current=false;setBusy(false);}}
async function persist(next:WorkoutDraft){await setPreference('workoutDraft',next);setDraft(next);}
function choose(name:string){const exercise=catalog.find(r=>r.payload.name===name)?.payload;const p=draft.prescriptions?.find(e=>e.name===name);change({...empty,exercise:name,mode:p?.trackingMode||exercise?.trackingMode||'weight_reps',rest:String(p?.restSec??exercise?.defaultRestSec??90),tempo:p?.tempo||exercise?.defaultTempo||'',index:1});}
async function skipMovement(name:string){const planned=draft.prescriptions?.find(item=>item.name===name);const existing=draft.logs.find(log=>log.name===name);if(existing?.sets.length)throw new Error('A movement with logged sets cannot be marked skipped. Undo its sets first.');const logs=draft.logs.filter(log=>log.name!==name);logs.push({...logFromPlan(name,planned),status:'skipped'});await persist({...draft,logs});}
async function logSet(){if(!entry.exercise.trim())throw new Error('Choose an exercise.');const set=parseWorkoutSet({s:1,w:entry.weight,r:entry.reps,durationSec:duration,rir:entry.rir||undefined,rpe:entry.rpe||undefined,type:entry.type,side:entry.side,tempo:entry.tempo,restSec:entry.rest},entry.mode);const logs=draft.logs.map(l=>({...l,sets:[...l.sets]}));let log=logs.find(l=>l.name===entry.exercise);if(!log){log=logFromPlan(entry.exercise,prescription);logs.push(log);}log.status='completed';log.sets.push({...set,s:log.sets.length+1});await persist({...draft,logs,setOrder:[...(draft.setOrder||[]),entry.exercise]});change({timerStart:null,duration:String(duration),index:2});const seconds=entry.rest.trim()===''?90:Number(entry.rest);await setPreference('restEndsAt',Date.now()+seconds*1000);setRestVersion(v=>v+1);try{await startRest(seconds);}catch{setError('Set saved. Rest countdown works; Android notifications are unavailable.');}}
async function finish(){if(!draft.logs.some(l=>l.sets.length))throw new Error('Record at least one set.');sessionInputSchema.parse(draft);const finishedAt=new Date().toISOString();const ready=rows<Readiness>('readiness').find(r=>r.payload.date===draft.date)?.payload;const payload:Session={...draft,status:'finished',createdAt:draft.startedAt,updatedAt:finishedAt,endedAt:finishedAt,durationMinutes:Math.round((Date.now()-Date.parse(draft.startedAt))/60000),weekId:draft.weekId||'mobile',weekName:draft.weekName||'Mobile workout',weekNumber:draft.weekNumber||1,dayKey:draft.dayKey||draft.id,dayTitle:draft.dayTitle||'Workout',name:String(rows<{displayName:string}>('profile')[0]?.payload.displayName||'Athlete'),sleep:ready?.sleepHours??'',soreness:ready?.soreness??'',readiness:ready||null};await saveRecord({id:draft.id,entityType:'session',payload,updatedAt:finishedAt,revision:1,deviceId:await deviceId()});await setPreference('workoutDraft',fresh());await setPreference('workoutEntryV4',empty);await refresh();nav.replace('Session',{id:draft.id});}
if(!loaded)return <Loading message={error||'Restoring your workout…'}/>;
const numberInput=(key:'weight'|'reps',title:string)=><Card style={{flex:1}}><Kicker>{title}</Kicker><Input label={title} numeric value={entry[key]} onChange={v=>change({[key]:v})}/><Row>{[-1,1].map(n=><Chip key={n} title={n<0?'−1':'+1'} onPress={()=>change({[key]:String(Math.max(0,(Number(entry[key])||0)+n))})}/>)}</Row></Card>;
return <Page><Kicker>Active session · {draft.date}</Kicker><Heading>{draft.dayTitle||'Your workout'}</Heading><FlashDeck label={entry.exercise||'CHOOSE MOVEMENT'} index={entry.index} onChange={index=>{if(entry.timerStart!==null)change({duration:String(duration),timerStart:null,index});else change({index});}} canNext={entry.index!==0||Boolean(entry.exercise)}>
<View style={{gap:16}}><Heading size={25}>Choose your movement.</Heading><Input label="Find an exercise" value={query} onChange={setQuery}/>{draft.planned?.map(name=>{const log=draft.logs.find(item=>item.name===name);return <Card key={name}><Kicker>{log?.status==='skipped'?'Skipped':log?.sets.length?`${log.sets.length} set${log.sets.length===1?'':'s'} logged`:'Planned movement'}</Kicker><Heading size={19}>{name}</Heading><Row><Action title="Train" secondary onPress={()=>choose(name)}/><Action title="Skip" secondary disabled={busy||log?.status==='skipped'} onPress={()=>void perform(()=>skipMovement(name))}/></Row></Card>;})}{catalog.filter(r=>r.payload.name.toLowerCase().includes(query.toLowerCase())).slice(0,12).map(r=><Action key={r.id} secondary title={r.payload.name} onPress={()=>choose(r.payload.name)}/>)}{query.trim()&&<Action title={`Use “${query.trim()}”`} onPress={()=>choose(query.trim())}/>}<Action title="Plans & scheduled workouts" secondary onPress={()=>nav.navigate('Plans')}/></View>
<View style={{gap:18}}><Kicker>Set {(currentLog?.sets.length||0)+1} · {entry.mode==='time'?'Timed hold':entry.mode==='reps'?'Repetitions':'Weighted set'}</Kicker><Heading>{entry.exercise}</Heading><Card><Kicker>Prescription target</Kicker><Label>{prescription?.vol||'Self-directed session'} {prescription?.target||''}</Label><Label muted>{prescription?.cue||'Record only the work you complete.'}</Label></Card>{last!=null&&<Card><Kicker>Previous actual · {last.date}</Kicker><Label>{last.logs.find(l=>l.name===entry.exercise)?.sets.map(s=>formatWorkoutSet(s,units)).join(' · ')}</Label></Card>}<Row wrap>{(['weight_reps','reps','time'] as const).map(m=><Chip key={m} title={m==='weight_reps'?'Weighted':m==='reps'?'Reps only':'Timed'} selected={entry.mode===m} onPress={()=>change({mode:m,timerStart:null,duration:String(duration)})}/>)}</Row>{entry.mode==='time'?<Card accent><Kicker>Actual hold time</Kicker><Heading size={48}>{Math.floor(duration/60)}:{String(duration%60).padStart(2,'0')}</Heading><Action title={entry.timerStart===null?'Start timer':'Pause timer'} secondary onPress={()=>entry.timerStart===null?change({timerBase:duration,timerStart:Date.now()}):change({duration:String(duration),timerStart:null})}/>{entry.timerStart===null&&<Input label="Actual seconds" numeric value={entry.duration} onChange={v=>change({duration:v})}/>}</Card>:<Row>{entry.mode==='weight_reps'&&numberInput('weight',`Load · ${units}`)}{numberInput('reps','Repetitions')}</Row>}<Card><Kicker>Effort · Reps in reserve</Kicker><Row wrap>{['0','1','2','3','4'].map(v=><Chip key={v} title={v==='4'?'4+':v} selected={entry.rir===v} onPress={()=>change({rir:v})}/>)}</Row><Input label="RPE (optional 1–10)" numeric value={entry.rpe} onChange={v=>change({rpe:v})}/></Card><Row wrap>{['warmup','work','amrap','drop','failure','backoff'].map(v=><Chip key={v} title={v} selected={entry.type===v} onPress={()=>change({type:v})}/>)}</Row><Row>{['both','L','R'].map(v=><Chip key={v} title={v==='both'?'Both sides':v} selected={entry.side===v} onPress={()=>change({side:v})}/>)}</Row><Input label="Rest seconds" numeric value={entry.rest} onChange={v=>change({rest:v})}/><Input label="Tempo" value={entry.tempo} onChange={v=>change({tempo:v})}/><Action title={busy?'Saving set…':'Log set & start rest'} disabled={busy} icon="check" onPress={()=>void perform(logSet)}/><WorkoutTools records={records} exercise={entry.exercise} units={units==='lb'?'lb':'kg'} onWarmup={(w,r)=>change({weight:w,reps:r,mode:'weight_reps',type:'warmup'})}/></View>
<View style={{gap:18}}><Kicker>Between sets</Kicker><Heading>Take your rest.</Heading><RestTimer refreshToken={restVersion} defaultSeconds={Number(entry.rest)||90}/><Card><Kicker>Next effort</Kicker><Heading size={23}>{entry.exercise}</Heading><Label muted>{prescription?.cue||'Return when you are ready for another quality set.'}</Label></Card><Action title="Next set" onPress={()=>change({index:1,duration:'',timerStart:null})}/><Action secondary title="Change exercise / queue" onPress={()=>change({index:0})}/></View>
<View style={{gap:18}}><Kicker>Finish review</Kicker><Heading>Look at the work you did.</Heading><Card><Row><Metric title="Movements" value={draft.logs.length}/><Metric title="Actual sets" value={draft.logs.reduce((n,l)=>n+l.sets.length,0)}/></Row></Card>{draft.logs.map(log=><Card key={log.name}><Heading size={20}>{log.name}</Heading>{log.status==='skipped'?<Label muted>Skipped — no work recorded</Label>:log.sets.map((s,i)=><Label key={i}>{i+1}. {formatWorkoutSet(s,units)}</Label>)}</Card>)}{draft.planned?.filter(name=>!draft.logs.some(log=>log.name===name)).map(name=><Label key={name} muted>Not logged: {name}</Label>)}<Action title="Undo last saved set" secondary disabled={busy||!draft.logs.some(l=>l.sets.length)} onPress={()=>void perform(async()=>{const logs=draft.logs.map(l=>({...l,sets:[...l.sets]}));const name=draft.setOrder?.at(-1),i=name?logs.findIndex(l=>l.name===name):logs.length-1;if(i<0)throw new Error('Last set not found.');logs[i].sets.pop();await persist({...draft,logs:logs.filter(l=>l.sets.length),setOrder:draft.setOrder?.slice(0,-1)});})}/><Action title="Finish & save workout" disabled={busy||!draft.logs.some(l=>l.sets.length)} onPress={()=>Alert.alert('Save this workout?','Only logged sets will count toward your history.',[{text:'Keep training',style:'cancel'},{text:'Finish workout',onPress:()=>void perform(finish)}])}/></View>
</FlashDeck>{Boolean(error)&&<Label>{error}</Label>}<Action title="Review session" secondary onPress={()=>change({index:3,timerStart:null,duration:String(duration)})}/></Page>;}
