import { useMemo, useState } from 'react';
import { Alert, Linking, Pressable, Switch, Text, TextInput, View } from 'react-native';
import { defaultExerciseCatalog } from '../../../../src/shared/exercise-catalog';
import type { Exercise } from '../../../../src/shared/types';
import type { SyncRecord } from '../../../../src/shared/sync';
import { deviceId, saveRecord } from '../lib/store';
import { RecordManager, type RecordSpec } from './RecordManager';
const spec:RecordSpec={type:'exercise',title:'Exercise details',defaults:{aliases:[],muscles:[],equipment:'',movementPattern:'',substitutions:[],trackingMode:'weight_reps'},fields:[{key:'name',label:'Name',required:true},{key:'aliases',label:'Other names',kind:'list'},{key:'muscles',label:'Muscles',kind:'list'},{key:'equipment',label:'Equipment'},{key:'movementPattern',label:'Movement pattern'},{key:'bodyPart',label:'Body part'},{key:'workoutSplit',label:'Workout split'},{key:'familyId',label:'Exercise family'},{key:'defaultCue',label:'Technique cue'},{key:'defaultRestSec',label:'Default rest (seconds)',kind:'number',min:0,max:86400},{key:'defaultTempo',label:'Default tempo'},{key:'trackingMode',label:'Tracking mode',options:['weight_reps','reps','time'],required:true},{key:'tutorialLink',label:'Tutorial URL'}]};
export function ExerciseLibrary({records,onSaved}:{records:SyncRecord[];onSaved:()=>Promise<void>}) {
  const [query,setQuery]=useState(''),[favorites,setFavorites]=useState(false),[limit,setLimit]=useState(20),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false);
  const catalog=useMemo(()=>{const map=new Map(defaultExerciseCatalog().map(e=>[e.id,{id:e.id,entityType:'exercise' as const,payload:e,revision:1,updatedAt:'',deviceId:'builtin'}]));for(const row of records.filter(r=>r.entityType==='exercise')){if(row.deletedAt)map.delete(row.id);else map.set(row.id,row as typeof map extends Map<string,infer V>?V:never);}return [...map.values()];},[records]);
  const matches=catalog.filter(r=>{const e=r.payload as Exercise;return !e.meta?.archived&&(!favorites||e.meta?.favorite)&&`${e.name} ${(e.aliases||[]).join(' ')} ${(e.muscles||[]).join(' ')} ${e.equipment}`.toLowerCase().includes(query.toLowerCase());});
  const row=catalog.find(r=>r.id===selected),exercise=row?.payload as Exercise|undefined;
  async function favorite(){if(!row||!exercise||busy)return;setBusy(true);try{const now=new Date().toISOString();await saveRecord({...row,payload:{...exercise,meta:{...exercise.meta,favorite:!exercise.meta?.favorite,updatedAt:now}},updatedAt:now,deviceId:await deviceId()});await onSaved();}catch(error){Alert.alert('Could not save',(error as Error).message);}finally{setBusy(false);}}
  return <View style={{padding:16,gap:10,backgroundColor:'#17191F',borderRadius:18}}><Text style={{color:'#9EEA22',fontSize:20}}>Exercise library</Text><TextInput accessibilityLabel="Search exercise library" value={query} onChangeText={v=>{setQuery(v);setLimit(20);}} placeholder="Name, muscle or equipment" placeholderTextColor="#A7ADB7" style={{padding:12,color:'#F6F7F8',borderWidth:1,borderColor:'#53645a'}}/><Text style={{color:'#A7ADB7'}}>Favourites only</Text><Switch accessibilityLabel="Favourites only" value={favorites} onValueChange={setFavorites}/>
    {matches.slice(0,limit).map(r=><Pressable accessibilityRole="button" key={r.id} style={{padding:14,backgroundColor:'#232A35',borderRadius:8}} onPress={()=>setSelected(r.id)}><Text style={{color:'#F6F7F8'}}>{(r.payload as Exercise).meta?.favorite?'★ ':''}{(r.payload as Exercise).name}</Text></Pressable>)}
    {matches.length>limit&&<Pressable accessibilityRole="button" style={{padding:14}} onPress={()=>setLimit(limit+20)}><Text style={{color:'#F6F7F8'}}>Show more ({matches.length} matches)</Text></Pressable>}
    {row&&exercise&&<><Text style={{color:'#F6F7F8'}}>{exercise.name}</Text><Pressable accessibilityRole="button" disabled={busy} style={{padding:14}} onPress={()=>void favorite()}><Text style={{color:'#F6F7F8'}}>{exercise.meta?.favorite?'Remove favourite':'Add favourite'}</Text></Pressable>{/^https?:\/\//i.test(exercise.tutorialLink||'')&&<Pressable accessibilityRole="link" style={{padding:14}} onPress={()=>void Linking.openURL(exercise.tutorialLink!).catch(()=>Alert.alert('Could not open tutorial'))}><Text style={{color:'#F6F7F8'}}>Open tutorial</Text></Pressable>}<RecordManager key={row.id} spec={spec} records={[row]} onSaved={onSaved}/></>}
    <RecordManager spec={{...spec,title:'Add custom exercise'}} records={[]} onSaved={onSaved}/>
  </View>;
}
