import {Children,useRef,type ReactNode} from 'react';
import {Animated,PanResponder,Pressable,StyleSheet,Text,View,AccessibilityInfo,Dimensions} from 'react-native';
export function FlashDeck({children,label,index,onChange,canNext=true}:{children:ReactNode;label:string;index:number;onChange:(n:number)=>void;canNext?:boolean}) {
 const cards=Children.toArray(children), x=useRef(new Animated.Value(0)).current;
 const state=useRef({index,count:cards.length,canNext,onChange});state.current={index,count:cards.length,canNext,onChange};
 const move=(delta:number)=>{const s=state.current,next=s.index+delta;if(next<0||next>=s.count||(delta>0&&!s.canNext)){Animated.spring(x,{toValue:0,useNativeDriver:true}).start();return;}s.onChange(next);x.setValue(0);AccessibilityInfo.announceForAccessibility(`${label}, card ${next+1} of ${s.count}`);};
 const pan=useRef(PanResponder.create({onMoveShouldSetPanResponder:(_,g)=>g.x0>28&&g.x0<Dimensions.get('window').width-28&&Math.abs(g.dx)>20&&Math.abs(g.dx)>Math.abs(g.dy)*2,onPanResponderMove:(_,g)=>x.setValue(Math.max(-90,Math.min(90,g.dx))),onPanResponderRelease:(_,g)=>{if(Math.abs(g.dx)>65&&Math.abs(g.dx)>Math.abs(g.dy)*1.5)move(g.dx<0?1:-1);else Animated.spring(x,{toValue:0,useNativeDriver:true}).start();},onPanResponderTerminate:()=>x.setValue(0)})).current;
 return <View style={s.deck}><View style={s.row}><Text style={s.eyebrow}>{label}</Text><Text style={s.eyebrow}>{index+1} / {cards.length}</Text></View><View style={s.progress}>{cards.map((_,i)=><View key={i} style={[s.segment,i<=index&&s.filled]}/>)}</View><View style={s.back}><Animated.View {...pan.panHandlers} style={[s.card,{transform:[{translateX:x}]}]}>{cards[index]}</Animated.View></View><View style={s.row}><Pressable accessibilityRole="button" accessibilityLabel="Previous card" disabled={index===0} onPress={()=>move(-1)} style={[s.button,index===0&&s.disabled]}><Text style={s.buttonText}>← Back</Text></Pressable><Text style={s.hint}>Swipe left to continue</Text><Pressable accessibilityRole="button" accessibilityLabel="Next card" disabled={index===cards.length-1||!canNext} onPress={()=>move(1)} style={[s.button,(index===cards.length-1||!canNext)&&s.disabled]}><Text style={s.buttonText}>Next →</Text></Pressable></View></View>;
}
const s=StyleSheet.create({deck:{gap:18},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8},eyebrow:{color:'#A7ADB7',fontSize:12,fontWeight:'700',letterSpacing:1},progress:{flexDirection:'row',gap:4},segment:{height:4,borderRadius:4,flex:1,backgroundColor:'#2C3038'},filled:{backgroundColor:'#9EEA22'},back:{backgroundColor:'#202630',borderRadius:30,paddingBottom:8},card:{backgroundColor:'#17191F',borderWidth:1,borderColor:'#2C3038',borderRadius:28,minHeight:350,padding:24,gap:20},button:{paddingVertical:14,paddingHorizontal:18,backgroundColor:'#9EEA22',borderRadius:16},buttonText:{color:'#192414',fontWeight:'800'},disabled:{opacity:.35},hint:{color:'#A7ADB7',fontSize:10,flexShrink:1,textAlign:'center'}});
