import {useRef,useState} from 'react';
import {ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {deviceId,saveRecord,setPreference} from '../lib/store';
import type {SyncRecord} from '../../../../src/shared/sync';

export function Onboarding({records,onGoogle,onComplete,connected}:{records:SyncRecord[];onGoogle:()=>Promise<boolean>;onComplete:()=>Promise<void>;connected:boolean}) {
 const actionLock=useRef(false);
 const profile=records.find(r=>r.entityType==='profile'&&!r.deletedAt);
 const existing=profile?.payload as {displayName?:string;units?:string}|undefined;
 const [step,setStep]=useState(0),[name,setName]=useState(existing?.displayName||''),[units,setUnits]=useState(existing?.units||'kg'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function perform(action:()=>Promise<void>){if(actionLock.current)return;actionLock.current=true;setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{actionLock.current=false;setBusy(false);}}
 async function finish(){if(!name.trim())throw new Error('Enter the name you want to use in Body OS.');await saveRecord({id:profile?.id||'profile',entityType:'profile',payload:{...(profile?.payload as Record<string,unknown>||{}),displayName:name.trim(),units},updatedAt:new Date().toISOString(),revision:profile?.revision||1,deviceId:await deviceId()},true,profile?.revision||0);await setPreference('onboardingVersion',1);await onComplete();}
 const button=(label:string,action:()=>void,secondary=false)=><Pressable accessibilityRole="button" disabled={busy} onPress={action} style={[s.button,secondary&&s.secondary,busy&&{opacity:.5}]}><Text style={[s.buttonText,secondary&&{color:'#F6F7F8'}]}>{label}</Text></Pressable>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.brand}>BODY OS <Text style={{color:'#A7ADB7'}}> / 4.0</Text></Text><View style={s.steps}>{[0,1,2].map(i=><View key={i} style={[s.step,i<=step&&{backgroundColor:'#9EEA22'}]}/>)}</View>
 {step===0?<><Text style={s.eyebrow}>TRAINING + SKINCARE</Text><Text style={s.title}>Your body.{ '\n'}Your progress.{ '\n'}Your space.</Text><Text style={s.description}>A clearer way to train, recover and care for yourself. Start on this phone. Connect Google whenever you want to sync.</Text><View style={s.card}><Text style={s.cardTitle}>Built around your day</Text><Text style={s.description}>Log one set at a time. Keep your plans, progress and daily care together.</Text><Text style={s.cardTitle}>Available offline</Text><Text style={s.description}>Your local records stay usable without a connection.</Text></View>{button(connected?'Google connected · Continue':'Continue with Google',()=>void perform(async()=>{if(connected||await onGoogle())setStep(1);}))}{button('Continue without an account',()=>setStep(1),true)}</>:step===1?<><Text style={s.eyebrow}>MAKE IT YOURS</Text><Text style={s.title}>What should we{ '\n'}call you?</Text><Text style={s.description}>This name appears in your profile and reports. You can change it later.</Text><Text style={s.label}>Your name</Text><TextInput accessibilityLabel="Your name" value={name} onChangeText={setName} autoComplete="name" maxLength={100} style={s.input}/><Text style={s.label}>Training units</Text><View style={s.steps}>{['kg','lb'].map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{checked:units===value}} onPress={()=>setUnits(value)} style={[s.unit,units===value&&{borderColor:'#9EEA22'}]}><Text style={s.cardTitle}>{value==='kg'?'Kilograms':'Pounds'}</Text><Text style={s.description}>{value}</Text></Pressable>)}</View>{button('Continue',()=>{if(name.trim())setStep(2);else setError('Enter your name to continue.');})}{button('Back',()=>setStep(0),true)}</>:<><Text style={s.eyebrow}>READY WHEN YOU ARE</Text><Text style={s.title}>One good day{ '\n'}at a time.</Text>{[['01','Check in','Record how you feel before training.'],['02','Train','Log actual sets, take your rest and keep your progress.'],['03','Care','Build a consistent AM and PM routine.']].map(([n,title,detail])=><View key={n} style={s.card}><Text style={s.eyebrow}>{n}</Text><Text style={s.cardTitle}>{title}</Text><Text style={s.description}>{detail}</Text></View>)}{button('Enter Body OS',()=>void perform(finish))}{button('Back',()=>setStep(1),true)}</>}
 {busy&&<ActivityIndicator color="#9EEA22"/>}{Boolean(error)&&<Text accessibilityRole="alert" style={{color:'#FFB4AB',fontSize:16}}>{error}</Text>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#101115'},content:{padding:24,paddingTop:32,paddingBottom:48,gap:20},brand:{color:'#9EEA22',fontSize:16,fontWeight:'800',letterSpacing:2},eyebrow:{color:'#9EEA22',fontSize:12,fontWeight:'700',letterSpacing:1.5},title:{color:'#F6F7F8',fontSize:38,fontWeight:'800',letterSpacing:-1.4,lineHeight:44},description:{color:'#A7ADB7',fontSize:16,lineHeight:24},card:{backgroundColor:'#17191F',padding:20,borderRadius:24,gap:10,borderWidth:1,borderColor:'#2C3038'},cardTitle:{fontSize:19,fontWeight:'700',color:'#F6F7F8'},button:{backgroundColor:'#9EEA22',padding:18,minHeight:54,borderRadius:16,alignItems:'center'},secondary:{backgroundColor:'#1D2027',borderWidth:1,borderColor:'#2C3038'},buttonText:{color:'#152000',fontSize:16,fontWeight:'800'},steps:{flexDirection:'row',gap:10},step:{height:4,backgroundColor:'#2C3038',flex:1,borderRadius:2},input:{backgroundColor:'#1D2027',color:'#F6F7F8',fontSize:20,padding:18,borderRadius:16,borderWidth:1,borderColor:'#2C3038'},label:{fontSize:15,color:'#A7ADB7'},unit:{flex:1,padding:18,borderWidth:1,borderColor:'#2C3038',backgroundColor:'#17191F',borderRadius:16,gap:8}});
