import { useState } from 'react';
import { Alert, Pressable, Switch, Text, TextInput, View } from 'react-native';
import type { Program, Week, ProgramPhase } from '../../../../src/shared/types';
import type { SyncRecord } from '../../../../src/shared/sync';
import { deviceId, saveRecord } from '../lib/store';
function Button({label,action}:{label:string;action:()=>void}) {return <Pressable accessibilityRole="button" style={{padding:14,backgroundColor:'#232A35',borderRadius:10}} onPress={action}><Text style={{color:'#F6F7F8'}}>{label}</Text></Pressable>;}
export function ProgramManager({records,onSaved}:{records:SyncRecord[];onSaved:()=>Promise<void>}) {
  const [draft,setDraft]=useState<Program|null>(null),[busy,setBusy]=useState(false);
  const weeks=records.filter(r=>r.entityType==='week'&&!r.deletedAt).map(r=>r.payload as Week);
  const programs=records.filter(r=>r.entityType==='program'&&!r.deletedAt).map(r=>r.payload as Program);
  async function save(deleting=false){if(!draft||busy)return;setBusy(true);try{
    if(!deleting&&!draft.name.trim())throw new Error('Enter a program name.');
    const now=new Date().toISOString();await saveRecord({id:draft.id,entityType:'program',payload:{...draft,updatedAt:now},updatedAt:now,revision:1,deviceId:await deviceId(),...(deleting?{deletedAt:now}:{})});await onSaved();setDraft(null);
  }catch(error){Alert.alert('Program not saved',(error as Error).message);}finally{setBusy(false);}}
  const field=(key:'name'|'notes',label:string)=><View><Text style={{color:'#A7ADB7'}}>{label}</Text><TextInput accessibilityLabel={label} value={draft?.[key]||''} onChangeText={v=>draft&&setDraft({...draft,[key]:v})} style={{padding:12,color:'#F6F7F8',borderWidth:1,borderColor:'#53645a',borderRadius:8}}/></View>;
  return <View style={{padding:16,gap:10,backgroundColor:'#17191F',borderRadius:18}}><Text style={{color:'#9EEA22',fontSize:20}}>Programs</Text>{!draft?<><Button label="Create program" action={()=>setDraft({id:`program-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name:'',notes:'',weeks:[],active:true,createdAt:new Date().toISOString()})}/>{programs.map(p=><Button key={p.id} label={`${p.name} · ${p.weeks.length} weeks${p.archived?' · archived':''}`} action={()=>setDraft(JSON.parse(JSON.stringify(p)))}/>)}</>:<>{field('name','Program name')}{field('notes','Notes')}<Text style={{color:'#A7ADB7'}}>Active</Text><Switch accessibilityLabel="Active program" value={draft.active} onValueChange={active=>setDraft({...draft,active})}/><Text style={{color:'#A7ADB7'}}>Archived</Text><Switch accessibilityLabel="Archived program" value={Boolean(draft.archived)} onValueChange={archived=>setDraft({...draft,archived})}/>
    {draft.weeks.map((ref,index)=><View key={`${ref.weekId}-${index}`} style={{gap:8,paddingVertical:10}}><Text style={{color:'#F6F7F8'}}>Week {index+1}: {weeks.find(w=>w.id===ref.weekId)?.name||ref.name||'Missing plan'}</Text>{(['accumulate','intensify','deload','peak','other'] as ProgramPhase[]).map(phase=><Button key={phase} label={`${ref.phase===phase?'✓ ':''}${phase}`} action={()=>setDraft({...draft,weeks:draft.weeks.map((w,i)=>i===index?{...w,phase}:w)})}/>)}<Button label="Remove from program" action={()=>setDraft({...draft,weeks:draft.weeks.filter((_,i)=>i!==index).map((w,i)=>({...w,weekNumber:i+1}))})}/>{index>0&&<Button label="Move up" action={()=>{const refs=[...draft.weeks];[refs[index-1],refs[index]]=[refs[index],refs[index-1]];setDraft({...draft,weeks:refs.map((w,i)=>({...w,weekNumber:i+1}))});}}/>}</View>)}
    <Text style={{color:'#A7ADB7'}}>Add a saved plan as a program week</Text>{weeks.map(w=><Button key={w.id} label={`Add ${w.name}`} action={()=>setDraft({...draft,weeks:[...draft.weeks,{weekId:w.id,weekNumber:draft.weeks.length+1,phase:w.phase||'accumulate',name:w.name}]})}/>)}{!weeks.length&&<Text style={{color:'#A7ADB7'}}>Create a plan first.</Text>}
    <Button label={busy?'Saving…':'Save program'} action={()=>void save()}/><Button label="Cancel" action={()=>{if(!busy)Alert.alert('Discard edits?','Saved programs will remain unchanged.',[{text:'Keep editing',style:'cancel'},{text:'Discard',onPress:()=>setDraft(null)}]);}}/>{programs.some(p=>p.id===draft.id)&&<Button label="Delete program" action={()=>{if(!busy)Alert.alert('Delete program?','Saved plans and workout history will remain.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void save(true)}]);}}/>}
  </>}</View>;
}
