import type { FieldSpec, RecordSpec } from './RecordManager';
const text=(key:string,label:string,required=false):FieldSpec=>({key,label,required});
const number=(key:string,label:string,min=0,max=100000,required=false):FieldSpec=>({key,label,kind:'number',min,max,required});
const date:FieldSpec={key:'date',label:'Date',kind:'date',required:true};
const notes=text('notes','Notes');
export const progressSpecs:RecordSpec[]=[
  {type:'target',title:'Goals',defaults:{type:'strength',status:'active',current:0,unit:'kg'},fields:[text('name','Goal name',true),{key:'type',label:'Type',options:['strength','body','body-fat','habit','custom'],required:true},number('current','Current value',0,100000,true),number('target','Target value',0,100000,true),text('unit','Unit'),{key:'deadline',label:'Deadline',kind:'date'},{key:'status',label:'Status',options:['active','completed']},text('linkedExercise','Linked exercise name')]},
  {type:'goalCheckIn',title:'Goal check-ins',fields:[{key:'goalId',label:'Goal',reference:'target',required:true},date,number('value','Value',0,100000,true),text('note','Note')]},
  {type:'measurement',title:'Body measurements',defaults:{weight:''},fields:[date,number('weight','Body weight (your profile unit)',0.1,1500),number('waist','Waist (cm for kg profile; inches for lb)',0.1,500),number('neck','Neck',0.1,500),number('chest','Chest',0.1,500),number('arms','Arms',0.1,500),number('hips','Hips',0.1,500),number('bodyFat','Body fat (%)',0.1,100),number('muscleMass','Muscle mass',0,1500),number('waterPercentage','Water (%)',0.1,100),notes]},
  {type:'painLog',title:'Pain and injury log',defaults:{affectsTraining:false},fields:[date,text('region','Body region',true),number('severity','Severity (0–10)',0,10,true),{key:'affectsTraining',label:'Affects training',kind:'boolean'},notes]},
  {type:'cardio',title:'Cardio',fields:[date,text('activity','Activity',true),number('durationMinutes','Duration (minutes)',0.1,1440,true),number('distance','Distance (same unit as your web records)',0,10000),number('perceivedEffort','Effort (1–10)',1,10),notes]},
  {type:'habit',title:'Habits',defaults:{active:true,target:1,unit:'times'},fields:[text('name','Habit name',true),number('target','Daily target',0,100000,true),text('unit','Unit',true),{key:'active',label:'Active',kind:'boolean'}]},
  {type:'habitLog',title:'Habit entries',fields:[{key:'habitId',label:'Habit',reference:'habit',required:true},date,number('value','Amount completed',0,100000,true)]},
  {type:'weeklyReview',title:'Weekly reviews',fields:[{key:'weekStart',label:'Week starting',kind:'date',required:true},text('wins','What went well'),text('blockers','What got in the way'),text('adjustment','Next adjustment')]},
];
export const careSpecs:RecordSpec[]=[
  {type:'skinProduct',title:'Products',defaults:{brand:'',category:'other',actives:[],usedIn:[],status:'active',openedAt:'',expiresAt:'',notes:'',pros:[],cons:[],useCase:'',bestFor:[]},fields:[text('name','Product name',true),text('brand','Brand'),{key:'category',label:'Category',options:['cleanser','toner','serum','moisturizer','sunscreen','treatment','exfoliant','mask','eye','other'],required:true},{key:'status',label:'Status',options:['active','paused','finished','wishlist'],required:true},{key:'actives',label:'Active ingredients',kind:'list'},{key:'openedAt',label:'Opened date',kind:'date'},{key:'expiresAt',label:'Expiry date',kind:'date'},{key:'pros',label:'Pros',kind:'list'},{key:'cons',label:'Cons',kind:'list'},text('useCase','Use case'),{key:'bestFor',label:'Best for',kind:'list'},notes]},
  {type:'skinProfile',title:'My skin',singleton:'skin-profile',defaults:{skinType:'unknown',concerns:[],sensitivities:[],goals:[],climate:'',notes:''},fields:[{key:'skinType',label:'Skin type',options:['unknown','normal','dry','oily','combination','sensitive'],required:true},{key:'concerns',label:'Concerns',kind:'list'},{key:'sensitivities',label:'Sensitivities',kind:'list'},{key:'goals',label:'Goals',kind:'list'},text('climate','Climate'),notes]},
];
export const profileSpec:RecordSpec={type:'profile',title:'Profile',singleton:'profile',defaults:{displayName:'',units:'kg'},fields:[text('displayName','Display name',true),{key:'units',label:'Weight unit',options:['kg','lb'],required:true},number('height','Height (cm for kg profile; inches for lb)',0.1,300)]};

export const scheduleSpec:RecordSpec={type:'scheduledWorkout',title:'Workout schedule',defaults:{status:'planned',notes:''},fields:[date,text('title','Workout title',true),{key:'weekId',label:'Plan',reference:'week'},{key:'dayKey',label:'Workout day',dayOf:'weekId'},{key:'status',label:'Status',options:['planned','done','skipped','rescheduled'],required:true},notes]};
