import {useEffect,useState} from 'react';
import {Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import type {ExerciseTrackingMode} from '../../../../src/shared/types';
export function SetEntry({mode,onMode,weight,onWeight,reps,onReps,duration,onDuration,units}:{mode:ExerciseTrackingMode;onMode:(m:ExerciseTrackingMode)=>void;weight:string;onWeight:(v:string)=>void;reps:string;onReps:(v:string)=>void;duration:string;onDuration:(v:string)=>void;units:string}){
 const [started,setStarted]=useState<number|null>(null),[base,setBase]=useState(0);
 useEffect(()=>{if(started===null)return;const tick=()=>onDuration(String(base+Math.floor((Date.now()-started)/1000)));tick();const timer=setInterval(tick,250);return()=>clearInterval(timer);},[started,base,onDuration]);
 useEffect(()=>{setStarted(null);},[mode]);
 function change(m:ExerciseTrackingMode){setStarted(null);onMode(m);}
 const input=(label:string,value:string,changeValue:(v:string)=>void)=><View style={s.inputCard}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} keyboardType="decimal-pad" style={s.number} value={value} onChangeText={changeValue} selectTextOnFocus/><View style={s.row}>{[-1,1].map(delta=><Pressable accessibilityRole="button" accessibilityLabel={`${delta<0?'Decrease':'Increase'} ${label}`} key={delta} onPress={()=>changeValue(String(Math.max(0,(Number(value)||0)+delta)))} style={s.adjust}><Text style={s.text}>{delta<0?'−':'+'}</Text></Pressable>)}</View></View>;
 return <View style={{gap:20}}><View style={s.row}>{(['weight_reps','reps','time'] as const).map(m=><Pressable accessibilityRole="radio" accessibilityState={{checked:mode===m}} key={m} onPress={()=>change(m)} style={[s.mode,mode===m&&s.active]}><Text style={[s.label,mode===m&&{color:'#9EEA22'}]}>{m==='weight_reps'?'Weighted':m==='reps'?'Reps only':'Timed'}</Text></Pressable>)}</View>
 {mode==='time'?<View style={s.timer}><Text style={s.label}>ACTUAL TIME</Text><Text style={s.clock}>{Math.floor((Number(duration)||0)/60)}:{String((Number(duration)||0)%60).padStart(2,'0')}</Text><Pressable accessibilityRole="button" onPress={()=>{if(started!==null){onDuration(String(base+Math.floor((Date.now()-started)/1000)));setStarted(null);}else{setBase(Number(duration)||0);setStarted(Date.now());}}} style={s.timerButton}><Text style={s.dark}>{started===null?'Start timer':'Pause timer'}</Text></Pressable>{started===null&&input('Duration in seconds',duration,onDuration)}<Text style={s.label}>Pause before continuing. Only Log set saves this effort.</Text></View>:<View style={s.row}>{mode==='weight_reps'&&input(`Load · ${units}`,weight,onWeight)}{input('Repetitions',reps,onReps)}</View>}
 </View>;
}
const s=StyleSheet.create({row:{flexDirection:'row',gap:10},mode:{flex:1,paddingVertical:14,alignItems:'center',borderRadius:12,backgroundColor:'#232A35',borderWidth:1,borderColor:'#2C3038'},active:{borderColor:'#9EEA22',backgroundColor:'#242E18'},label:{color:'#A7ADB7',fontSize:13,lineHeight:20},inputCard:{flex:1,backgroundColor:'#11141A',padding:14,borderRadius:20,gap:12},number:{fontSize:36,fontWeight:'800',color:'#F6F7F8',paddingVertical:12,minWidth:60},adjust:{backgroundColor:'#232A35',flex:1,minHeight:48,alignItems:'center',justifyContent:'center',borderRadius:12},text:{color:'#F6F7F8',fontSize:24},timer:{padding:20,borderWidth:2,borderColor:'#9EEA22',borderRadius:28,gap:16},clock:{fontSize:54,fontWeight:'800',color:'#F6F7F8',textAlign:'center'},timerButton:{backgroundColor:'#9EEA22',padding:16,borderRadius:14,alignItems:'center'},dark:{color:'#152000',fontWeight:'800',fontSize:16}});
