import { getDb } from '../db/connection.js';
import { id } from '../lib/ids.js';

export interface KnowledgeHit { documentId: string; title: string; excerpt: string; score: number; source: string; }
function ensureTables(){getDb().exec(`CREATE TABLE IF NOT EXISTS knowledge_documents (id TEXT PRIMARY KEY,title TEXT NOT NULL,source_type TEXT NOT NULL,source_ref TEXT DEFAULT '',created_at TEXT NOT NULL); CREATE VIRTUAL TABLE IF NOT EXISTS knowledge_chunks USING fts5(document_id UNINDEXED,title,content);`);}
function chunks(content: string) { const words=content.replace(/\s+/g,' ').trim().split(' '); const result:string[]=[]; for(let i=0;i<words.length;i+=180) result.push(words.slice(i,i+220).join(' ')); return result.filter(Boolean); }
export function addKnowledgeDocument(input:{title:string;content:string;sourceType?:string;sourceRef?:string}) { ensureTables();const title=input.title.trim();const content=input.content.trim();if(!title||!content)throw new Error('A title and document text are required.');if(content.length>2_000_000)throw new Error('Document text exceeds the 2 MB local import limit.');const documentId=id('doc'),db=getDb(),now=new Date().toISOString();db.prepare('INSERT INTO knowledge_documents(id,title,source_type,source_ref,created_at) VALUES(?,?,?,?,?)').run(documentId,title,input.sourceType||'text',input.sourceRef||'',now);const insert=db.prepare('INSERT INTO knowledge_chunks(document_id,title,content) VALUES(?,?,?)');for(const chunk of chunks(content))insert.run(documentId,title,chunk);return {documentId,chunks:chunks(content).length}; }
export function searchKnowledge(query:string,limit=6):KnowledgeHit[]{ensureTables();const terms=query.trim().replace(/[^\p{L}\p{N}\s]/gu,' ').split(/\s+/).filter(term=>term.length>1).map(term=>`"${term.replace(/"/g,'')}"`).join(' OR ');if(!terms)return [];const rows=getDb().prepare(`SELECT c.document_id AS documentId,c.title AS title, snippet(knowledge_chunks,2,'<mark>','</mark>','…',18) AS excerpt, bm25(knowledge_chunks) AS score,d.source_ref AS source FROM knowledge_chunks c JOIN knowledge_documents d ON d.id=c.document_id WHERE knowledge_chunks MATCH ? ORDER BY score LIMIT ?`).all(terms,Math.max(1,Math.min(limit,12))) as unknown as KnowledgeHit[];return rows;}
export function listKnowledgeDocuments(){ensureTables();return getDb().prepare('SELECT id,title,source_type AS sourceType,source_ref AS sourceRef,created_at AS createdAt,(SELECT count(*) FROM knowledge_chunks WHERE document_id=knowledge_documents.id) AS chunks FROM knowledge_documents ORDER BY created_at DESC').all();}
export function removeKnowledgeDocument(documentId:string){ensureTables();const db=getDb();db.prepare('DELETE FROM knowledge_chunks WHERE document_id=?').run(documentId);db.prepare('DELETE FROM knowledge_documents WHERE id=?').run(documentId);}
