import type {ReactNode} from 'react';
import {ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,ScrollView,Text,TextInput,View,type TextStyle,type ViewStyle} from 'react-native';
import Svg,{Path,Circle} from 'react-native-svg';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {fonts,useTheme} from './theme';
export function Label({children,muted=false,accent=false,size=15,style}:{children:ReactNode;muted?:boolean;accent?:boolean;size?:number;style?:TextStyle}){const t=useTheme();return <Text style={{fontFamily:fonts.body,color:accent?t.lime:muted?t.muted:t.text,fontSize:size,lineHeight:size*1.45,...style}}>{children}</Text>;}
export function Heading({children,size=28}:{children:ReactNode;size?:number}){const t=useTheme();return <Text accessibilityRole="header" style={{fontFamily:fonts.display,color:t.text,fontSize:size,lineHeight:size*1.2,letterSpacing:-.6}}>{children}</Text>;}
export function Kicker({children}:{children:ReactNode}){return <Label accent size={11} style={{fontFamily:fonts.bold,letterSpacing:1.3,textTransform:'uppercase'}}>{children}</Label>;}
export function Card({children,style,accent=false}:{children:ReactNode;style?:ViewStyle;accent?:boolean}){const t=useTheme();return <View style={{backgroundColor:t.panel,padding:18,borderRadius:18,borderWidth:1,borderColor:accent?t.lime:t.line,gap:12,...style}}>{children}</View>;}
export function Row({children,wrap=false}:{children:ReactNode;wrap?:boolean}){return <View style={{flexDirection:'row',gap:10,alignItems:'center',flexWrap:wrap?'wrap':'nowrap'}}>{children}</View>;}
export function Action({title,onPress,secondary=false,disabled=false,icon}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;icon?:string}){const t=useTheme();return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>({backgroundColor:secondary?t.raised:t.lime,paddingHorizontal:18,paddingVertical:15,minHeight:50,borderRadius:12,opacity:disabled?.4:pressed?.75:1,flexDirection:'row',gap:10,alignItems:'center',justifyContent:'center'})}>{icon!=null&&icon!==''&&<Icon name={icon} color={secondary?t.text:t.onLime}/>}<Text style={{fontFamily:fonts.bold,fontSize:15,color:secondary?t.text:t.onLime,textAlign:'center'}}>{title}</Text></Pressable>;}
export function Chip({title,selected,onPress}:{title:string;selected?:boolean;onPress:()=>void}){const t=useTheme();return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={{backgroundColor:selected?t.lime:t.raised,minHeight:44,paddingHorizontal:14,paddingVertical:10,borderRadius:12}}><Text style={{color:selected?t.onLime:t.text,fontFamily:fonts.medium,fontSize:13}}>{title}</Text></Pressable>;}
export function Input({label,value,onChange,numeric=false,multiline=false,secret=false}:{label:string;value:string;onChange:(v:string)=>void;numeric?:boolean;multiline?:boolean;secret?:boolean}){const t=useTheme();return <View style={{gap:7}}><Label muted size={13}>{label}</Label><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} keyboardType={numeric?'decimal-pad':'default'} multiline={multiline} secureTextEntry={secret} autoCapitalize="none" placeholderTextColor={t.muted} style={{backgroundColor:t.low,color:t.text,fontFamily:fonts.body,fontSize:17,minHeight:52,padding:14,borderRadius:12,borderWidth:1,borderColor:t.line,textAlignVertical:multiline?'top':'center'}}/></View>;}
export function Metric({title,value,unit}:{title:string;value:string|number;unit?:string}){const t=useTheme();return <View style={{flex:1,gap:5,minWidth:90}}><Label muted size={11}>{title.toUpperCase()}</Label><Text style={{fontFamily:fonts.display,color:t.text,fontSize:28}}>{value}<Text style={{fontFamily:fonts.body,fontSize:12,color:t.muted}}> {unit}</Text></Text></View>;}
export function Destination({title,detail,icon='arrow',onPress}:{title:string;detail?:string;icon?:string;onPress:()=>void}){const t=useTheme();return <Pressable accessibilityRole="button" onPress={onPress} style={{backgroundColor:t.panel,borderColor:t.line,borderWidth:1,borderRadius:16,padding:17,minHeight:70,flexDirection:'row',gap:14,alignItems:'center'}}><Icon name={icon} color={t.lime}/><View style={{flex:1,gap:3}}><Label style={{fontFamily:fonts.heading}}>{title}</Label>{Boolean(detail)&&<Label muted size={12}>{detail}</Label>}</View><Icon name="arrow" color={t.muted}/></Pressable>;}
export function Empty({title,detail,action,onPress}:{title:string;detail:string;action?:string;onPress?:()=>void}){return <Card><Heading size={21}>{title}</Heading><Label muted>{detail}</Label>{action&&onPress&&<Action title={action} onPress={onPress}/>}</Card>;}
export function Page({children}:{children:ReactNode}){const t=useTheme(),insets=useSafeAreaInsets();return <KeyboardAvoidingView style={{flex:1,backgroundColor:t.background}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:18,paddingBottom:Math.max(28,insets.bottom+20),gap:18}}>{children}</ScrollView></KeyboardAvoidingView>;}
export function Loading({message='Loading your records…'}:{message?:string}){return <Page><ActivityIndicator/><Label muted>{message}</Label></Page>;}
export function Ring({value,label}:{value:number;label:string}){const t=useTheme(),progress=Math.min(100,Math.max(0,value));return <View style={{width:170,height:170,alignSelf:'center',alignItems:'center',justifyContent:'center'}}><Svg width={170} height={170} style={{position:'absolute'}}><Circle cx={85} cy={85} r={72} fill="none" stroke={t.raised} strokeWidth={9}/><Circle cx={85} cy={85} r={72} fill="none" stroke={t.lime} strokeWidth={9} strokeDasharray={`${progress*4.5239} 452.39`} strokeLinecap="round" rotation={-90} origin="85,85"/></Svg><Heading size={34}>{Math.round(progress)}</Heading><Label muted size={12}>{label}</Label></View>;}
const paths:Record<string,string>={home:'M3 10 12 3l9 7v10H15v-6H9v6H3Z',train:'m6 4 2 2-2 2-2-2m14 10 2 2-2 2-2-2M7 7l10 10M3 9l6-6m6 18 6-6',progress:'M4 20V4m0 16h17M7 15l4-5 4 2 5-8',care:'M12 3s-7 8-7 12a7 7 0 0 0 14 0c0-4-7-12-7-12Z',more:'M4 6h16M4 12h16M4 18h16',arrow:'m9 5 7 7-7 7',back:'m15 5-7 7 7 7',calendar:'M5 5h14v16H5ZM8 2v6m8-6v6M5 10h14',shield:'m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6Z',clock:'M12 6v6l4 2',check:'m5 12 4 4L20 5',book:'M3 4h7l2 2 2-2h7v16h-7l-2 2-2-2H3ZM12 6v16',cloud:'M6 18a5 5 0 1 1 1-10 6 6 0 0 1 11 2 4 4 0 1 1 0 8ZM12 10v7',person:'M4 21v-3c0-5 16-5 16 0v3',plus:'M12 4v16M4 12h16',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1Z'};
export function Icon({name,color,size=23}:{name:string;color:string;size?:number}){return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={1.7} strokeLinecap="round" strokeLinejoin="round"><Path d={paths[name]||paths.arrow}/>{name==='person'&&<Circle cx={12} cy={7} r={4}/>}{name==='clock'&&<Circle cx={12} cy={12} r={9}/>}</Svg>;}
