; Auto-generated by build-installer.cjs — do not edit by hand
; Workout OS 2.4.0

#define MyAppName "Workout OS"
#define MyAppVersion "2.4.0"
#define MyAppPublisher "Workout OS"
#define MyAppURL "http://127.0.0.1:10000"
#define MyAppExeName "start.bat"

[Setup]
AppId={{A7C3E8F1-4B2D-4E9A-9C1F-8D6B5A0E2F73}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
DefaultDirName={autopf}\Workout OS
DefaultGroupName={#MyAppName}
; ALWAYS show the directory selection page
DisableDirPage=no
DisableProgramGroupPage=yes
AllowNoIcons=yes
OutputDir=E:/Workout OS/release
OutputBaseFilename=WorkoutOS-Setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\src\client\public\favicon.ico
SetupLogging=yes
CloseApplications=yes
RestartApplications=no
; Keep user training data across upgrades
UsePreviousAppDir=yes
DirExistsWarning=auto

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Messages]
WelcomeLabel2=This will install [name/ver] on your computer.%n%nWorkout OS runs locally at http://127.0.0.1:10000 and keeps your database on this PC.%n%nIMPORTANT: Node.js 20 or newer must be installed on this computer.%nDownload it from https://nodejs.org/ if you have not already.%n%nIt is recommended that you close any running Workout OS window before continuing.
FinishedLabel=Setup has finished installing [name] on your computer.%n%nStart Workout OS from the desktop shortcut, then open http://127.0.0.1:10000 if the browser does not open automatically.

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"; Flags: checkedonce

[Dirs]
; CRITICAL: user training data — never remove on uninstall/upgrade
Name: "{app}\data"; Flags: uninsneveruninstall
Name: "{app}\backups"; Flags: uninsneveruninstall

[Files]
; Complete app payload from the staging directory.
; Existing data\ and backups\ on disk are left untouched (not in this source).
Source: "E:/Workout OS/installer/stage\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "data\*,backups\*,src\server\db\workout.db,*.db,*.db-wal,*.db-shm,.env"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Comment: "Start Workout OS (http://127.0.0.1:10000)"
Name: "{group}\Stop {#MyAppName}"; Filename: "{app}\stop.bat"; WorkingDir: "{app}"; Comment: "Stop Workout OS server"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon; Comment: "Start Workout OS"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch Workout OS now"; Flags: nowait postinstall skipifsilent shellexec; WorkingDir: "{app}"

[InstallDelete]
; Only remove obsolete APP artifacts. NEVER data or backups.
; (Intentionally does not list {app}\data or {app}\backups)

[UninstallDelete]
; App runtime only — data/backups protected by uninsneveruninstall
Type: filesandordirs; Name: "{app}\dist"
Type: filesandordirs; Name: "{app}\node_modules"
Type: filesandordirs; Name: "{app}\src"
Type: filesandordirs; Name: "{app}\installer"
Type: filesandordirs; Name: "{app}\release"
Type: filesandordirs; Name: "{app}\docs"
; DO NOT add {app}\data or {app}\backups here

[Code]
function IsNodeJsInstalled(): Boolean;
var
  ResultCode: Integer;
begin
  Result := Exec('cmd.exe', '/C where node >nul 2>nul', '', SW_HIDE, ewWaitUntilTerminated, ResultCode)
            and (ResultCode = 0);
end;

function InitializeSetup(): Boolean;
begin
  Result := True;

  if not IsNodeJsInstalled() then
  begin
    if MsgBox(
      'Node.js was NOT detected on this computer.' + #13#10 + #13#10 +
      'Workout OS requires Node.js 20 or newer to run.' + #13#10 +
      'You can download it from https://nodejs.org/' + #13#10 + #13#10 +
      'Do you want to continue the installation anyway?' + #13#10 +
      '(You must install Node.js before launching Workout OS)',
      mbConfirmation, MB_YESNO) = IDNO then
    begin
      Result := False;
    end;
  end;
end;

// Extra safety: never let uninstall wipe the SQLite DB
function InitializeUninstall(): Boolean;
begin
  Result := True;
end;
